# 
# Copyright (c) 2023, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This tool was automatically generated by:
#     q2wdl (version: 0.1.0)
# for:
#     qiime2 (version: 2023.2.0)
# 


version 1.0

struct qiime2_sample_classifier_summarize_params {
    File sample_estimator
    String visualization
}

task qiime2_sample_classifier_summarize {

    input {
        File sample_estimator
        String visualization
    }

    qiime2_sample_classifier_summarize_params task_params = object {
        sample_estimator: sample_estimator,
        visualization: visualization
    }

    command {
        q2dataflow q2wdl run sample_classifier summarize ~{write_json(task_params)}
    }

    output {
        File visualization_file = "~{visualization}"
    }

}


workflow wkflw_qiime2_sample_classifier_summarize {
input {
        File sample_estimator
        String visualization
    }

    call qiime2_sample_classifier_summarize {
        input: sample_estimator=sample_estimator, visualization=visualization
    }

}
