# 
# Copyright (c) 2024, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This template was automatically generated by:
#     q2dataflow wdl (version: 0.2.0)
# for:
#     qiime2 (version: 2024.2.0)
# 


version 1.0

struct qiime2_feature_table_split_params {
    File table
    String metadata
    File q2wdl_metafile_metadata
    Boolean filter_empty_features
    String tables
}

task qiime2_feature_table_split {

    input {
        File table
        String metadata
        File q2wdl_metafile_metadata
        Boolean filter_empty_features = true
        String tables
    }

    qiime2_feature_table_split_params task_params = object {
        table: table,
        metadata: metadata,
        q2wdl_metafile_metadata: q2wdl_metafile_metadata,
        filter_empty_features: filter_empty_features,
        tables: tables
    }

    command {
        q2dataflow wdl run feature_table split ~{write_json(task_params)}
    }

    

}


workflow wkflw_qiime2_feature_table_split {
input {
        File table
        String metadata
        File q2wdl_metafile_metadata
        Boolean filter_empty_features = true
        String tables
    }

    call qiime2_feature_table_split {
        input: table=table, metadata=metadata, q2wdl_metafile_metadata=q2wdl_metafile_metadata, filter_empty_features=filter_empty_features, tables=tables
    }

}
