# 
# Copyright (c) 2024, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This template was automatically generated by:
#     q2dataflow wdl (version: 0.2.0)
# for:
#     qiime2 (version: 2024.2.0)
# 


version 1.0

struct qiime2_feature_table_filter_samples_params {
    File table
    Int min_frequency
    Int? max_frequency
    Int min_features
    Int? max_features
    Array[File]? q2wdl_metafile_metadata
    String? where
    Boolean exclude_ids
    Boolean filter_empty_features
    Boolean allow_empty_table
    String filtered_table
}

task qiime2_feature_table_filter_samples {

    input {
        File table
        Int min_frequency = 0
        Int? max_frequency
        Int min_features = 0
        Int? max_features
        Array[File]? q2wdl_metafile_metadata
        String? where
        Boolean exclude_ids = false
        Boolean filter_empty_features = true
        Boolean allow_empty_table = false
        String filtered_table
    }

    qiime2_feature_table_filter_samples_params task_params = object {
        table: table,
        min_frequency: min_frequency,
        max_frequency: max_frequency,
        min_features: min_features,
        max_features: max_features,
        q2wdl_metafile_metadata: q2wdl_metafile_metadata,
        where: where,
        exclude_ids: exclude_ids,
        filter_empty_features: filter_empty_features,
        allow_empty_table: allow_empty_table,
        filtered_table: filtered_table
    }

    command {
        q2dataflow wdl run feature_table filter_samples ~{write_json(task_params)}
    }

    output {
        File filtered_table_file = "~{filtered_table}"
    }

}


workflow wkflw_qiime2_feature_table_filter_samples {
input {
        File table
        Int min_frequency = 0
        Int? max_frequency
        Int min_features = 0
        Int? max_features
        Array[File]? q2wdl_metafile_metadata
        String? where
        Boolean exclude_ids = false
        Boolean filter_empty_features = true
        Boolean allow_empty_table = false
        String filtered_table
    }

    call qiime2_feature_table_filter_samples {
        input: table=table, min_frequency=min_frequency, max_frequency=max_frequency, min_features=min_features, max_features=max_features, q2wdl_metafile_metadata=q2wdl_metafile_metadata, where=where, exclude_ids=exclude_ids, filter_empty_features=filter_empty_features, allow_empty_table=allow_empty_table, filtered_table=filtered_table
    }

}
