# 
# Copyright (c) 2024, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This template was automatically generated by:
#     q2dataflow wdl (version: 0.2.0)
# for:
#     qiime2 (version: 2024.2.0)
# 


version 1.0

struct qiime2_feature_table_merge_taxa_params {
    Array[File] data
    String merged_data
}

task qiime2_feature_table_merge_taxa {

    input {
        Array[File] data
        String merged_data
    }

    qiime2_feature_table_merge_taxa_params task_params = object {
        data: data,
        merged_data: merged_data
    }

    command {
        q2dataflow wdl run feature_table merge_taxa ~{write_json(task_params)}
    }

    output {
        File merged_data_file = "~{merged_data}"
    }

}


workflow wkflw_qiime2_feature_table_merge_taxa {
input {
        Array[File] data
        String merged_data
    }

    call qiime2_feature_table_merge_taxa {
        input: data=data, merged_data=merged_data
    }

}
