# 
# Copyright (c) 2024, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This template was automatically generated by:
#     q2dataflow wdl (version: 0.2.0)
# for:
#     qiime2 (version: 2024.2.0)
# 


version 1.0

struct qiime2_feature_table_summarize_params {
    File table
    Array[File]? q2wdl_metafile_sample_metadata
    String visualization
}

task qiime2_feature_table_summarize {

    input {
        File table
        Array[File]? q2wdl_metafile_sample_metadata
        String visualization
    }

    qiime2_feature_table_summarize_params task_params = object {
        table: table,
        q2wdl_metafile_sample_metadata: q2wdl_metafile_sample_metadata,
        visualization: visualization
    }

    command {
        q2dataflow wdl run feature_table summarize ~{write_json(task_params)}
    }

    output {
        File visualization_file = "~{visualization}"
    }

}


workflow wkflw_qiime2_feature_table_summarize {
input {
        File table
        Array[File]? q2wdl_metafile_sample_metadata
        String visualization
    }

    call qiime2_feature_table_summarize {
        input: table=table, q2wdl_metafile_sample_metadata=q2wdl_metafile_sample_metadata, visualization=visualization
    }

}
