# 
# Copyright (c) 2024, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This template was automatically generated by:
#     q2dataflow wdl (version: 0.2.0)
# for:
#     qiime2 (version: 2024.2.0)
# 


version 1.0

struct qiime2_feature_table_rename_ids_params {
    File table
    String metadata
    File q2wdl_metafile_metadata
    String axis
    Boolean strict
    String renamed_table
}

task qiime2_feature_table_rename_ids {

    input {
        File table
        String metadata
        File q2wdl_metafile_metadata
        String axis = "sample"
        Boolean strict = false
        String renamed_table
    }

    qiime2_feature_table_rename_ids_params task_params = object {
        table: table,
        metadata: metadata,
        q2wdl_metafile_metadata: q2wdl_metafile_metadata,
        axis: axis,
        strict: strict,
        renamed_table: renamed_table
    }

    command {
        q2dataflow wdl run feature_table rename_ids ~{write_json(task_params)}
    }

    output {
        File renamed_table_file = "~{renamed_table}"
    }

}


workflow wkflw_qiime2_feature_table_rename_ids {
input {
        File table
        String metadata
        File q2wdl_metafile_metadata
        String axis = "sample"
        Boolean strict = false
        String renamed_table
    }

    call qiime2_feature_table_rename_ids {
        input: table=table, metadata=metadata, q2wdl_metafile_metadata=q2wdl_metafile_metadata, axis=axis, strict=strict, renamed_table=renamed_table
    }

}
