# 
# Copyright (c) 2024, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This template was automatically generated by:
#     q2dataflow wdl (version: 0.2.0)
# for:
#     qiime2 (version: 2024.2.0)
# 


version 1.0

struct qiime2_feature_table_relative_frequency_params {
    File table
    String relative_frequency_table
}

task qiime2_feature_table_relative_frequency {

    input {
        File table
        String relative_frequency_table
    }

    qiime2_feature_table_relative_frequency_params task_params = object {
        table: table,
        relative_frequency_table: relative_frequency_table
    }

    command {
        q2dataflow wdl run feature_table relative_frequency ~{write_json(task_params)}
    }

    output {
        File relative_frequency_table_file = "~{relative_frequency_table}"
    }

}


workflow wkflw_qiime2_feature_table_relative_frequency {
input {
        File table
        String relative_frequency_table
    }

    call qiime2_feature_table_relative_frequency {
        input: table=table, relative_frequency_table=relative_frequency_table
    }

}
