# 
# Copyright (c) 2024, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This template was automatically generated by:
#     q2dataflow wdl (version: 0.2.0)
# for:
#     qiime2 (version: 2024.2.0)
# 


version 1.0

struct qiime2_feature_table_transpose_params {
    File table
    String transposed_feature_table
}

task qiime2_feature_table_transpose {

    input {
        File table
        String transposed_feature_table
    }

    qiime2_feature_table_transpose_params task_params = object {
        table: table,
        transposed_feature_table: transposed_feature_table
    }

    command {
        q2dataflow wdl run feature_table transpose ~{write_json(task_params)}
    }

    output {
        File transposed_feature_table_file = "~{transposed_feature_table}"
    }

}


workflow wkflw_qiime2_feature_table_transpose {
input {
        File table
        String transposed_feature_table
    }

    call qiime2_feature_table_transpose {
        input: table=table, transposed_feature_table=transposed_feature_table
    }

}
