# 
# Copyright (c) 2023, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This tool was automatically generated by:
#     q2wdl (version: 0.1.0)
# for:
#     qiime2 (version: 2023.2.0)
# 


version 1.0

struct qiime2_gneiss_ilr_phylogenetic_ordination_params {
    File table
    File tree
    Float pseudocount
    Int top_k_var
    Array[String]? clades
    String ordination
    String bifurcated_tree
    String clade_metadata
}

task qiime2_gneiss_ilr_phylogenetic_ordination {

    input {
        File table
        File tree
        Float pseudocount = 0.5
        Int top_k_var = 10
        Array[String]? clades
        String ordination
        String bifurcated_tree
        String clade_metadata
    }

    qiime2_gneiss_ilr_phylogenetic_ordination_params task_params = object {
        table: table,
        tree: tree,
        pseudocount: pseudocount,
        top_k_var: top_k_var,
        clades: clades,
        ordination: ordination,
        bifurcated_tree: bifurcated_tree,
        clade_metadata: clade_metadata
    }

    command {
        q2dataflow q2wdl run gneiss ilr_phylogenetic_ordination ~{write_json(task_params)}
    }

    output {
        File ordination_file = "~{ordination}"
        File bifurcated_tree_file = "~{bifurcated_tree}"
        File clade_metadata_file = "~{clade_metadata}"
    }

}


workflow wkflw_qiime2_gneiss_ilr_phylogenetic_ordination {
input {
        File table
        File tree
        Float pseudocount = 0.5
        Int top_k_var = 10
        Array[String]? clades
        String ordination
        String bifurcated_tree
        String clade_metadata
    }

    call qiime2_gneiss_ilr_phylogenetic_ordination {
        input: table=table, tree=tree, pseudocount=pseudocount, top_k_var=top_k_var, clades=clades, ordination=ordination, bifurcated_tree=bifurcated_tree, clade_metadata=clade_metadata
    }

}
