# 
# Copyright (c) 2023, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This tool was automatically generated by:
#     q2wdl (version: 0.1.0)
# for:
#     qiime2 (version: 2023.2.0)
# 


version 1.0

struct qiime2_gneiss_assign_ids_params {
    File input_table
    File input_tree
    String output_table
    String output_tree
}

task qiime2_gneiss_assign_ids {

    input {
        File input_table
        File input_tree
        String output_table
        String output_tree
    }

    qiime2_gneiss_assign_ids_params task_params = object {
        input_table: input_table,
        input_tree: input_tree,
        output_table: output_table,
        output_tree: output_tree
    }

    command {
        q2dataflow q2wdl run gneiss assign_ids ~{write_json(task_params)}
    }

    output {
        File output_table_file = "~{output_table}"
        File output_tree_file = "~{output_tree}"
    }

}


workflow wkflw_qiime2_gneiss_assign_ids {
input {
        File input_table
        File input_tree
        String output_table
        String output_tree
    }

    call qiime2_gneiss_assign_ids {
        input: input_table=input_table, input_tree=input_tree, output_table=output_table, output_tree=output_tree
    }

}
