# 
# Copyright (c) 2023, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This tool was automatically generated by:
#     q2wdl (version: 0.1.0)
# for:
#     qiime2 (version: 2023.2.0)
# 


version 1.0

struct qiime2_gneiss_dendrogram_heatmap_params {
    File table
    File tree
    String metadata
    File q2wdl_metafile_metadata
    Float pseudocount
    Int ndim
    String method
    String color_map
    String visualization
}

task qiime2_gneiss_dendrogram_heatmap {

    input {
        File table
        File tree
        String metadata
        File q2wdl_metafile_metadata
        Float pseudocount = 0.5
        Int ndim = 10
        String method = "clr"
        String color_map = "viridis"
        String visualization
    }

    qiime2_gneiss_dendrogram_heatmap_params task_params = object {
        table: table,
        tree: tree,
        metadata: metadata,
        q2wdl_metafile_metadata: q2wdl_metafile_metadata,
        pseudocount: pseudocount,
        ndim: ndim,
        method: method,
        color_map: color_map,
        visualization: visualization
    }

    command {
        q2dataflow q2wdl run gneiss dendrogram_heatmap ~{write_json(task_params)}
    }

    output {
        File visualization_file = "~{visualization}"
    }

}


workflow wkflw_qiime2_gneiss_dendrogram_heatmap {
input {
        File table
        File tree
        String metadata
        File q2wdl_metafile_metadata
        Float pseudocount = 0.5
        Int ndim = 10
        String method = "clr"
        String color_map = "viridis"
        String visualization
    }

    call qiime2_gneiss_dendrogram_heatmap {
        input: table=table, tree=tree, metadata=metadata, q2wdl_metafile_metadata=q2wdl_metafile_metadata, pseudocount=pseudocount, ndim=ndim, method=method, color_map=color_map, visualization=visualization
    }

}
