# 
# Copyright (c) 2023, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This tool was automatically generated by:
#     q2wdl (version: 0.1.0)
# for:
#     qiime2 (version: 2023.2.0)
# 


version 1.0

struct qiime2_quality_filter_q_score_params {
    File demux
    Int min_quality
    Int quality_window
    Float min_length_fraction
    Int max_ambiguous
    String filtered_sequences
    String filter_stats
}

task qiime2_quality_filter_q_score {

    input {
        File demux
        Int min_quality = 4
        Int quality_window = 3
        Float min_length_fraction = 0.75
        Int max_ambiguous = 0
        String filtered_sequences
        String filter_stats
    }

    qiime2_quality_filter_q_score_params task_params = object {
        demux: demux,
        min_quality: min_quality,
        quality_window: quality_window,
        min_length_fraction: min_length_fraction,
        max_ambiguous: max_ambiguous,
        filtered_sequences: filtered_sequences,
        filter_stats: filter_stats
    }

    command {
        q2dataflow q2wdl run quality_filter q_score ~{write_json(task_params)}
    }

    output {
        File filtered_sequences_file = "~{filtered_sequences}"
        File filter_stats_file = "~{filter_stats}"
    }

}


workflow wkflw_qiime2_quality_filter_q_score {
input {
        File demux
        Int min_quality = 4
        Int quality_window = 3
        Float min_length_fraction = 0.75
        Int max_ambiguous = 0
        String filtered_sequences
        String filter_stats
    }

    call qiime2_quality_filter_q_score {
        input: demux=demux, min_quality=min_quality, quality_window=quality_window, min_length_fraction=min_length_fraction, max_ambiguous=max_ambiguous, filtered_sequences=filtered_sequences, filter_stats=filter_stats
    }

}
