# 
# Copyright (c) 2024, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This template was automatically generated by:
#     q2dataflow wdl (version: 0.2.0)
# for:
#     qiime2 (version: 2024.2.0)
# 


version 1.0

struct qiime2_fragment_insertion_classify_otus_experimental_params {
    File representative_sequences
    File tree
    File reference_taxonomy
    String classification
}

task qiime2_fragment_insertion_classify_otus_experimental {

    input {
        File representative_sequences
        File tree
        File reference_taxonomy
        String classification
    }

    qiime2_fragment_insertion_classify_otus_experimental_params task_params = object {
        representative_sequences: representative_sequences,
        tree: tree,
        reference_taxonomy: reference_taxonomy,
        classification: classification
    }

    command {
        q2dataflow wdl run fragment_insertion classify_otus_experimental ~{write_json(task_params)}
    }

    output {
        File classification_file = "~{classification}"
    }

}


workflow wkflw_qiime2_fragment_insertion_classify_otus_experimental {
input {
        File representative_sequences
        File tree
        File reference_taxonomy
        String classification
    }

    call qiime2_fragment_insertion_classify_otus_experimental {
        input: representative_sequences=representative_sequences, tree=tree, reference_taxonomy=reference_taxonomy, classification=classification
    }

}
