# 
# Copyright (c) 2024, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This template was automatically generated by:
#     q2dataflow wdl (version: 0.2.0)
# for:
#     qiime2 (version: 2024.2.0)
# 


version 1.0

struct qiime2_phylogeny_midpoint_root_params {
    File tree
    String rooted_tree
}

task qiime2_phylogeny_midpoint_root {

    input {
        File tree
        String rooted_tree
    }

    qiime2_phylogeny_midpoint_root_params task_params = object {
        tree: tree,
        rooted_tree: rooted_tree
    }

    command {
        q2dataflow wdl run phylogeny midpoint_root ~{write_json(task_params)}
    }

    output {
        File rooted_tree_file = "~{rooted_tree}"
    }

}


workflow wkflw_qiime2_phylogeny_midpoint_root {
input {
        File tree
        String rooted_tree
    }

    call qiime2_phylogeny_midpoint_root {
        input: tree=tree, rooted_tree=rooted_tree
    }

}
