# 
# Copyright (c) 2024, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This template was automatically generated by:
#     q2dataflow wdl (version: 0.2.0)
# for:
#     qiime2 (version: 2024.2.0)
# 


version 1.0

struct qiime2_phylogeny_raxml_params {
    File alignment
    Int? seed
    Int n_searches
    Int n_threads
    String raxml_version
    String substitution_model
    String tree
}

task qiime2_phylogeny_raxml {

    input {
        File alignment
        Int? seed
        Int n_searches = 1
        Int n_threads = 1
        String raxml_version = "Standard"
        String substitution_model = "GTRGAMMA"
        String tree
    }

    qiime2_phylogeny_raxml_params task_params = object {
        alignment: alignment,
        seed: seed,
        n_searches: n_searches,
        n_threads: n_threads,
        raxml_version: raxml_version,
        substitution_model: substitution_model,
        tree: tree
    }

    command {
        q2dataflow wdl run phylogeny raxml ~{write_json(task_params)}
    }

    output {
        File tree_file = "~{tree}"
    }

}


workflow wkflw_qiime2_phylogeny_raxml {
input {
        File alignment
        Int? seed
        Int n_searches = 1
        Int n_threads = 1
        String raxml_version = "Standard"
        String substitution_model = "GTRGAMMA"
        String tree
    }

    call qiime2_phylogeny_raxml {
        input: alignment=alignment, seed=seed, n_searches=n_searches, n_threads=n_threads, raxml_version=raxml_version, substitution_model=substitution_model, tree=tree
    }

}
