# 
# Copyright (c) 2024, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This template was automatically generated by:
#     q2dataflow wdl (version: 0.2.0)
# for:
#     qiime2 (version: 2024.2.0)
# 


version 1.0

struct qiime2_phylogeny_align_to_tree_mafft_fasttree_params {
    File sequences
    Int n_threads
    Float mask_max_gap_frequency
    Float mask_min_conservation
    Boolean parttree
    String alignment
    String masked_alignment
    String tree
    String rooted_tree
}

task qiime2_phylogeny_align_to_tree_mafft_fasttree {

    input {
        File sequences
        Int n_threads = 1
        Float mask_max_gap_frequency = 1.0
        Float mask_min_conservation = 0.4
        Boolean parttree = false
        String alignment
        String masked_alignment
        String tree
        String rooted_tree
    }

    qiime2_phylogeny_align_to_tree_mafft_fasttree_params task_params = object {
        sequences: sequences,
        n_threads: n_threads,
        mask_max_gap_frequency: mask_max_gap_frequency,
        mask_min_conservation: mask_min_conservation,
        parttree: parttree,
        alignment: alignment,
        masked_alignment: masked_alignment,
        tree: tree,
        rooted_tree: rooted_tree
    }

    command {
        q2dataflow wdl run phylogeny align_to_tree_mafft_fasttree ~{write_json(task_params)}
    }

    output {
        File alignment_file = "~{alignment}"
        File masked_alignment_file = "~{masked_alignment}"
        File tree_file = "~{tree}"
        File rooted_tree_file = "~{rooted_tree}"
    }

}


workflow wkflw_qiime2_phylogeny_align_to_tree_mafft_fasttree {
input {
        File sequences
        Int n_threads = 1
        Float mask_max_gap_frequency = 1.0
        Float mask_min_conservation = 0.4
        Boolean parttree = false
        String alignment
        String masked_alignment
        String tree
        String rooted_tree
    }

    call qiime2_phylogeny_align_to_tree_mafft_fasttree {
        input: sequences=sequences, n_threads=n_threads, mask_max_gap_frequency=mask_max_gap_frequency, mask_min_conservation=mask_min_conservation, parttree=parttree, alignment=alignment, masked_alignment=masked_alignment, tree=tree, rooted_tree=rooted_tree
    }

}
