# 
# Copyright (c) 2024, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This template was automatically generated by:
#     q2dataflow wdl (version: 0.2.0)
# for:
#     qiime2 (version: 2024.2.0)
# 


version 1.0

struct qiime2_phylogeny_raxml_rapid_bootstrap_params {
    File alignment
    Int? seed
    Int? rapid_bootstrap_seed
    Int bootstrap_replicates
    Int n_threads
    String raxml_version
    String substitution_model
    String tree
}

task qiime2_phylogeny_raxml_rapid_bootstrap {

    input {
        File alignment
        Int? seed
        Int? rapid_bootstrap_seed
        Int bootstrap_replicates = 100
        Int n_threads = 1
        String raxml_version = "Standard"
        String substitution_model = "GTRGAMMA"
        String tree
    }

    qiime2_phylogeny_raxml_rapid_bootstrap_params task_params = object {
        alignment: alignment,
        seed: seed,
        rapid_bootstrap_seed: rapid_bootstrap_seed,
        bootstrap_replicates: bootstrap_replicates,
        n_threads: n_threads,
        raxml_version: raxml_version,
        substitution_model: substitution_model,
        tree: tree
    }

    command {
        q2dataflow wdl run phylogeny raxml_rapid_bootstrap ~{write_json(task_params)}
    }

    output {
        File tree_file = "~{tree}"
    }

}


workflow wkflw_qiime2_phylogeny_raxml_rapid_bootstrap {
input {
        File alignment
        Int? seed
        Int? rapid_bootstrap_seed
        Int bootstrap_replicates = 100
        Int n_threads = 1
        String raxml_version = "Standard"
        String substitution_model = "GTRGAMMA"
        String tree
    }

    call qiime2_phylogeny_raxml_rapid_bootstrap {
        input: alignment=alignment, seed=seed, rapid_bootstrap_seed=rapid_bootstrap_seed, bootstrap_replicates=bootstrap_replicates, n_threads=n_threads, raxml_version=raxml_version, substitution_model=substitution_model, tree=tree
    }

}
