# 
# Copyright (c) 2024, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This template was automatically generated by:
#     q2dataflow wdl (version: 0.2.0)
# for:
#     qiime2 (version: 2024.2.0)
# 


version 1.0

struct qiime2_alignment_mask_params {
    File alignment
    Float max_gap_frequency
    Float min_conservation
    String masked_alignment
}

task qiime2_alignment_mask {

    input {
        File alignment
        Float max_gap_frequency = 1.0
        Float min_conservation = 0.4
        String masked_alignment
    }

    qiime2_alignment_mask_params task_params = object {
        alignment: alignment,
        max_gap_frequency: max_gap_frequency,
        min_conservation: min_conservation,
        masked_alignment: masked_alignment
    }

    command {
        q2dataflow wdl run alignment mask ~{write_json(task_params)}
    }

    output {
        File masked_alignment_file = "~{masked_alignment}"
    }

}


workflow wkflw_qiime2_alignment_mask {
input {
        File alignment
        Float max_gap_frequency = 1.0
        Float min_conservation = 0.4
        String masked_alignment
    }

    call qiime2_alignment_mask {
        input: alignment=alignment, max_gap_frequency=max_gap_frequency, min_conservation=min_conservation, masked_alignment=masked_alignment
    }

}
