# 
# Copyright (c) 2024, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This template was automatically generated by:
#     q2dataflow wdl (version: 0.2.0)
# for:
#     qiime2 (version: 2024.2.0)
# 


version 1.0

struct qiime2_alignment_mafft_params {
    File sequences
    Int n_threads
    Boolean parttree
    String alignment
}

task qiime2_alignment_mafft {

    input {
        File sequences
        Int n_threads = 1
        Boolean parttree = false
        String alignment
    }

    qiime2_alignment_mafft_params task_params = object {
        sequences: sequences,
        n_threads: n_threads,
        parttree: parttree,
        alignment: alignment
    }

    command {
        q2dataflow wdl run alignment mafft ~{write_json(task_params)}
    }

    output {
        File alignment_file = "~{alignment}"
    }

}


workflow wkflw_qiime2_alignment_mafft {
input {
        File sequences
        Int n_threads = 1
        Boolean parttree = false
        String alignment
    }

    call qiime2_alignment_mafft {
        input: sequences=sequences, n_threads=n_threads, parttree=parttree, alignment=alignment
    }

}
