# 
# Copyright (c) 2024, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This template was automatically generated by:
#     q2dataflow wdl (version: 0.2.0)
# for:
#     qiime2 (version: 2024.2.0)
# 


version 1.0

struct qiime2_quality_control_decontam_identify_batches_params {
    File table
    Array[File] q2wdl_metafile_metadata
    String split_column
    String method
    Boolean? filter_empty_features
    String? freq_concentration_column
    String? prev_control_column
    String? prev_control_indicator
    Float threshold
    Boolean weighted
    Float bin_size
    String batch_subset_tables
    String decontam_scores
    String score_histograms
}

task qiime2_quality_control_decontam_identify_batches {

    input {
        File table
        Array[File] q2wdl_metafile_metadata
        String split_column
        String method
        Boolean? filter_empty_features
        String? freq_concentration_column
        String? prev_control_column
        String? prev_control_indicator
        Float threshold = 0.1
        Boolean weighted = true
        Float bin_size = 0.02
        String batch_subset_tables
        String decontam_scores
        String score_histograms
    }

    qiime2_quality_control_decontam_identify_batches_params task_params = object {
        table: table,
        q2wdl_metafile_metadata: q2wdl_metafile_metadata,
        split_column: split_column,
        method: method,
        filter_empty_features: filter_empty_features,
        freq_concentration_column: freq_concentration_column,
        prev_control_column: prev_control_column,
        prev_control_indicator: prev_control_indicator,
        threshold: threshold,
        weighted: weighted,
        bin_size: bin_size,
        batch_subset_tables: batch_subset_tables,
        decontam_scores: decontam_scores,
        score_histograms: score_histograms
    }

    command {
        q2dataflow wdl run quality_control decontam_identify_batches ~{write_json(task_params)}
    }

    output {
        File score_histograms_file = "~{score_histograms}"
    }

}


workflow wkflw_qiime2_quality_control_decontam_identify_batches {
input {
        File table
        Array[File] q2wdl_metafile_metadata
        String split_column
        String method
        Boolean? filter_empty_features
        String? freq_concentration_column
        String? prev_control_column
        String? prev_control_indicator
        Float threshold = 0.1
        Boolean weighted = true
        Float bin_size = 0.02
        String batch_subset_tables
        String decontam_scores
        String score_histograms
    }

    call qiime2_quality_control_decontam_identify_batches {
        input: table=table, q2wdl_metafile_metadata=q2wdl_metafile_metadata, split_column=split_column, method=method, filter_empty_features=filter_empty_features, freq_concentration_column=freq_concentration_column, prev_control_column=prev_control_column, prev_control_indicator=prev_control_indicator, threshold=threshold, weighted=weighted, bin_size=bin_size, batch_subset_tables=batch_subset_tables, decontam_scores=decontam_scores, score_histograms=score_histograms
    }

}
