# 
# Copyright (c) 2024, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This template was automatically generated by:
#     q2dataflow wdl (version: 0.2.0)
# for:
#     qiime2 (version: 2024.2.0)
# 


version 1.0

struct qiime2_quality_control_decontam_remove_params {
    File decontam_scores
    File table
    Float threshold
    String filtered_table
}

task qiime2_quality_control_decontam_remove {

    input {
        File decontam_scores
        File table
        Float threshold = 0.1
        String filtered_table
    }

    qiime2_quality_control_decontam_remove_params task_params = object {
        decontam_scores: decontam_scores,
        table: table,
        threshold: threshold,
        filtered_table: filtered_table
    }

    command {
        q2dataflow wdl run quality_control decontam_remove ~{write_json(task_params)}
    }

    output {
        File filtered_table_file = "~{filtered_table}"
    }

}


workflow wkflw_qiime2_quality_control_decontam_remove {
input {
        File decontam_scores
        File table
        Float threshold = 0.1
        String filtered_table
    }

    call qiime2_quality_control_decontam_remove {
        input: decontam_scores=decontam_scores, table=table, threshold=threshold, filtered_table=filtered_table
    }

}
