# 
# Copyright (c) 2024, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This template was automatically generated by:
#     q2dataflow wdl (version: 0.2.0)
# for:
#     qiime2 (version: 2024.2.0)
# 


version 1.0

struct qiime2_quality_control_filter_reads_params {
    File demultiplexed_sequences
    File database
    Int n_threads
    String mode
    String sensitivity
    Int ref_gap_open_penalty
    Int ref_gap_ext_penalty
    Boolean exclude_seqs
    String filtered_sequences
}

task qiime2_quality_control_filter_reads {

    input {
        File demultiplexed_sequences
        File database
        Int n_threads = 1
        String mode = "local"
        String sensitivity = "sensitive"
        Int ref_gap_open_penalty = 5
        Int ref_gap_ext_penalty = 3
        Boolean exclude_seqs = true
        String filtered_sequences
    }

    qiime2_quality_control_filter_reads_params task_params = object {
        demultiplexed_sequences: demultiplexed_sequences,
        database: database,
        n_threads: n_threads,
        mode: mode,
        sensitivity: sensitivity,
        ref_gap_open_penalty: ref_gap_open_penalty,
        ref_gap_ext_penalty: ref_gap_ext_penalty,
        exclude_seqs: exclude_seqs,
        filtered_sequences: filtered_sequences
    }

    command {
        q2dataflow wdl run quality_control filter_reads ~{write_json(task_params)}
    }

    output {
        File filtered_sequences_file = "~{filtered_sequences}"
    }

}


workflow wkflw_qiime2_quality_control_filter_reads {
input {
        File demultiplexed_sequences
        File database
        Int n_threads = 1
        String mode = "local"
        String sensitivity = "sensitive"
        Int ref_gap_open_penalty = 5
        Int ref_gap_ext_penalty = 3
        Boolean exclude_seqs = true
        String filtered_sequences
    }

    call qiime2_quality_control_filter_reads {
        input: demultiplexed_sequences=demultiplexed_sequences, database=database, n_threads=n_threads, mode=mode, sensitivity=sensitivity, ref_gap_open_penalty=ref_gap_open_penalty, ref_gap_ext_penalty=ref_gap_ext_penalty, exclude_seqs=exclude_seqs, filtered_sequences=filtered_sequences
    }

}
