# 
# Copyright (c) 2024, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This template was automatically generated by:
#     q2dataflow wdl (version: 0.2.0)
# for:
#     qiime2 (version: 2024.2.0)
# 


version 1.0

struct qiime2_quality_control_decontam_score_viz_params {
    String decontam_scores
    String table
    Float threshold
    Boolean weighted
    Float bin_size
    String visualization
}

task qiime2_quality_control_decontam_score_viz {

    input {
        String decontam_scores
        String table
        Float threshold = 0.1
        Boolean weighted = true
        Float bin_size = 0.02
        String visualization
    }

    qiime2_quality_control_decontam_score_viz_params task_params = object {
        decontam_scores: decontam_scores,
        table: table,
        threshold: threshold,
        weighted: weighted,
        bin_size: bin_size,
        visualization: visualization
    }

    command {
        q2dataflow wdl run quality_control decontam_score_viz ~{write_json(task_params)}
    }

    output {
        File visualization_file = "~{visualization}"
    }

}


workflow wkflw_qiime2_quality_control_decontam_score_viz {
input {
        String decontam_scores
        String table
        Float threshold = 0.1
        Boolean weighted = true
        Float bin_size = 0.02
        String visualization
    }

    call qiime2_quality_control_decontam_score_viz {
        input: decontam_scores=decontam_scores, table=table, threshold=threshold, weighted=weighted, bin_size=bin_size, visualization=visualization
    }

}
