# 
# Copyright (c) 2023, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This tool was automatically generated by:
#     q2wdl (version: 0.1.0)
# for:
#     qiime2 (version: 2023.2.0)
# 


version 1.0

struct qiime2_taxa_filter_table_params {
    File table
    File taxonomy
    String? include
    String? exclude
    String query_delimiter
    String mode
    String filtered_table
}

task qiime2_taxa_filter_table {

    input {
        File table
        File taxonomy
        String? include
        String? exclude
        String query_delimiter = ","
        String mode = "contains"
        String filtered_table
    }

    qiime2_taxa_filter_table_params task_params = object {
        table: table,
        taxonomy: taxonomy,
        include: include,
        exclude: exclude,
        query_delimiter: query_delimiter,
        mode: mode,
        filtered_table: filtered_table
    }

    command {
        q2dataflow q2wdl run taxa filter_table ~{write_json(task_params)}
    }

    output {
        File filtered_table_file = "~{filtered_table}"
    }

}


workflow wkflw_qiime2_taxa_filter_table {
input {
        File table
        File taxonomy
        String? include
        String? exclude
        String query_delimiter = ","
        String mode = "contains"
        String filtered_table
    }

    call qiime2_taxa_filter_table {
        input: table=table, taxonomy=taxonomy, include=include, exclude=exclude, query_delimiter=query_delimiter, mode=mode, filtered_table=filtered_table
    }

}
