# 
# Copyright (c) 2023, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This tool was automatically generated by:
#     q2wdl (version: 0.1.0)
# for:
#     qiime2 (version: 2023.2.0)
# 


version 1.0

struct qiime2_taxa_collapse_params {
    File table
    File taxonomy
    Int level
    String collapsed_table
}

task qiime2_taxa_collapse {

    input {
        File table
        File taxonomy
        Int level
        String collapsed_table
    }

    qiime2_taxa_collapse_params task_params = object {
        table: table,
        taxonomy: taxonomy,
        level: level,
        collapsed_table: collapsed_table
    }

    command {
        q2dataflow q2wdl run taxa collapse ~{write_json(task_params)}
    }

    output {
        File collapsed_table_file = "~{collapsed_table}"
    }

}


workflow wkflw_qiime2_taxa_collapse {
input {
        File table
        File taxonomy
        Int level
        String collapsed_table
    }

    call qiime2_taxa_collapse {
        input: table=table, taxonomy=taxonomy, level=level, collapsed_table=collapsed_table
    }

}
