# 
# Copyright (c) 2023, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This tool was automatically generated by:
#     q2wdl (version: 0.1.0)
# for:
#     qiime2 (version: 2023.2.0)
# 


version 1.0

struct qiime2_taxa_barplot_params {
    File table
    File taxonomy
    Array[File]? q2wdl_metafile_metadata
    String visualization
}

task qiime2_taxa_barplot {

    input {
        File table
        File taxonomy
        Array[File]? q2wdl_metafile_metadata
        String visualization
    }

    qiime2_taxa_barplot_params task_params = object {
        table: table,
        taxonomy: taxonomy,
        q2wdl_metafile_metadata: q2wdl_metafile_metadata,
        visualization: visualization
    }

    command {
        q2dataflow q2wdl run taxa barplot ~{write_json(task_params)}
    }

    output {
        File visualization_file = "~{visualization}"
    }

}


workflow wkflw_qiime2_taxa_barplot {
input {
        File table
        File taxonomy
        Array[File]? q2wdl_metafile_metadata
        String visualization
    }

    call qiime2_taxa_barplot {
        input: table=table, taxonomy=taxonomy, q2wdl_metafile_metadata=q2wdl_metafile_metadata, visualization=visualization
    }

}
