# 
# Copyright (c) 2023, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This tool was automatically generated by:
#     q2wdl (version: 0.1.0)
# for:
#     qiime2 (version: 2023.2.0)
# 


version 1.0

struct qiime2_diversity_mantel_params {
    File dm1
    File dm2
    String method
    Int permutations
    Boolean intersect_ids
    String label1
    String label2
    String visualization
}

task qiime2_diversity_mantel {

    input {
        File dm1
        File dm2
        String method = "spearman"
        Int permutations = 999
        Boolean intersect_ids = false
        String label1 = "Distance Matrix 1"
        String label2 = "Distance Matrix 2"
        String visualization
    }

    qiime2_diversity_mantel_params task_params = object {
        dm1: dm1,
        dm2: dm2,
        method: method,
        permutations: permutations,
        intersect_ids: intersect_ids,
        label1: label1,
        label2: label2,
        visualization: visualization
    }

    command {
        q2dataflow q2wdl run diversity mantel ~{write_json(task_params)}
    }

    output {
        File visualization_file = "~{visualization}"
    }

}


workflow wkflw_qiime2_diversity_mantel {
input {
        File dm1
        File dm2
        String method = "spearman"
        Int permutations = 999
        Boolean intersect_ids = false
        String label1 = "Distance Matrix 1"
        String label2 = "Distance Matrix 2"
        String visualization
    }

    call qiime2_diversity_mantel {
        input: dm1=dm1, dm2=dm2, method=method, permutations=permutations, intersect_ids=intersect_ids, label1=label1, label2=label2, visualization=visualization
    }

}
