# 
# Copyright (c) 2023, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This tool was automatically generated by:
#     q2wdl (version: 0.1.0)
# for:
#     qiime2 (version: 2023.2.0)
# 


version 1.0

struct qiime2_diversity_alpha_params {
    File table
    String metric
    String alpha_diversity
}

task qiime2_diversity_alpha {

    input {
        File table
        String metric
        String alpha_diversity
    }

    qiime2_diversity_alpha_params task_params = object {
        table: table,
        metric: metric,
        alpha_diversity: alpha_diversity
    }

    command {
        q2dataflow q2wdl run diversity alpha ~{write_json(task_params)}
    }

    output {
        File alpha_diversity_file = "~{alpha_diversity}"
    }

}


workflow wkflw_qiime2_diversity_alpha {
input {
        File table
        String metric
        String alpha_diversity
    }

    call qiime2_diversity_alpha {
        input: table=table, metric=metric, alpha_diversity=alpha_diversity
    }

}
