# 
# Copyright (c) 2023, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This tool was automatically generated by:
#     q2wdl (version: 0.1.0)
# for:
#     qiime2 (version: 2023.2.0)
# 


version 1.0

struct qiime2_diversity_beta_rarefaction_params {
    File table
    File? phylogeny
    String metric
    String clustering_method
    Array[File] q2wdl_metafile_metadata
    Int sampling_depth
    Int iterations
    String correlation_method
    String color_scheme
    String visualization
}

task qiime2_diversity_beta_rarefaction {

    input {
        File table
        File? phylogeny
        String metric
        String clustering_method
        Array[File] q2wdl_metafile_metadata
        Int sampling_depth
        Int iterations = 10
        String correlation_method = "spearman"
        String color_scheme = "BrBG"
        String visualization
    }

    qiime2_diversity_beta_rarefaction_params task_params = object {
        table: table,
        phylogeny: phylogeny,
        metric: metric,
        clustering_method: clustering_method,
        q2wdl_metafile_metadata: q2wdl_metafile_metadata,
        sampling_depth: sampling_depth,
        iterations: iterations,
        correlation_method: correlation_method,
        color_scheme: color_scheme,
        visualization: visualization
    }

    command {
        q2dataflow q2wdl run diversity beta_rarefaction ~{write_json(task_params)}
    }

    output {
        File visualization_file = "~{visualization}"
    }

}


workflow wkflw_qiime2_diversity_beta_rarefaction {
input {
        File table
        File? phylogeny
        String metric
        String clustering_method
        Array[File] q2wdl_metafile_metadata
        Int sampling_depth
        Int iterations = 10
        String correlation_method = "spearman"
        String color_scheme = "BrBG"
        String visualization
    }

    call qiime2_diversity_beta_rarefaction {
        input: table=table, phylogeny=phylogeny, metric=metric, clustering_method=clustering_method, q2wdl_metafile_metadata=q2wdl_metafile_metadata, sampling_depth=sampling_depth, iterations=iterations, correlation_method=correlation_method, color_scheme=color_scheme, visualization=visualization
    }

}
