# 
# Copyright (c) 2024, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This template was automatically generated by:
#     q2dataflow wdl (version: 0.2.0)
# for:
#     qiime2 (version: 2024.2.0)
# 


version 1.0

struct qiime2_taxa_filter_seqs_params {
    File sequences
    File taxonomy
    String? include
    String? exclude
    String query_delimiter
    String mode
    String filtered_sequences
}

task qiime2_taxa_filter_seqs {

    input {
        File sequences
        File taxonomy
        String? include
        String? exclude
        String query_delimiter = ","
        String mode = "contains"
        String filtered_sequences
    }

    qiime2_taxa_filter_seqs_params task_params = object {
        sequences: sequences,
        taxonomy: taxonomy,
        include: include,
        exclude: exclude,
        query_delimiter: query_delimiter,
        mode: mode,
        filtered_sequences: filtered_sequences
    }

    command {
        q2dataflow wdl run taxa filter_seqs ~{write_json(task_params)}
    }

    output {
        File filtered_sequences_file = "~{filtered_sequences}"
    }

}


workflow wkflw_qiime2_taxa_filter_seqs {
input {
        File sequences
        File taxonomy
        String? include
        String? exclude
        String query_delimiter = ","
        String mode = "contains"
        String filtered_sequences
    }

    call qiime2_taxa_filter_seqs {
        input: sequences=sequences, taxonomy=taxonomy, include=include, exclude=exclude, query_delimiter=query_delimiter, mode=mode, filtered_sequences=filtered_sequences
    }

}
