# 
# Copyright (c) 2023, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This tool was automatically generated by:
#     q2wdl (version: 0.1.0)
# for:
#     qiime2 (version: 2023.2.0)
# 


version 1.0

struct qiime2_emperor_procrustes_plot_params {
    File reference_pcoa
    File other_pcoa
    File? m2_stats
    Array[File] q2wdl_metafile_metadata
    Array[String]? custom_axes
    Boolean ignore_missing_samples
    String visualization
}

task qiime2_emperor_procrustes_plot {

    input {
        File reference_pcoa
        File other_pcoa
        File? m2_stats
        Array[File] q2wdl_metafile_metadata
        Array[String]? custom_axes
        Boolean ignore_missing_samples = false
        String visualization
    }

    qiime2_emperor_procrustes_plot_params task_params = object {
        reference_pcoa: reference_pcoa,
        other_pcoa: other_pcoa,
        m2_stats: m2_stats,
        q2wdl_metafile_metadata: q2wdl_metafile_metadata,
        custom_axes: custom_axes,
        ignore_missing_samples: ignore_missing_samples,
        visualization: visualization
    }

    command {
        q2dataflow q2wdl run emperor procrustes_plot ~{write_json(task_params)}
    }

    output {
        File visualization_file = "~{visualization}"
    }

}


workflow wkflw_qiime2_emperor_procrustes_plot {
input {
        File reference_pcoa
        File other_pcoa
        File? m2_stats
        Array[File] q2wdl_metafile_metadata
        Array[String]? custom_axes
        Boolean ignore_missing_samples = false
        String visualization
    }

    call qiime2_emperor_procrustes_plot {
        input: reference_pcoa=reference_pcoa, other_pcoa=other_pcoa, m2_stats=m2_stats, q2wdl_metafile_metadata=q2wdl_metafile_metadata, custom_axes=custom_axes, ignore_missing_samples=ignore_missing_samples, visualization=visualization
    }

}
