# 
# Copyright (c) 2023, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This tool was automatically generated by:
#     q2wdl (version: 0.1.0)
# for:
#     qiime2 (version: 2023.2.0)
# 


version 1.0

struct qiime2_emperor_plot_params {
    File pcoa
    Array[File] q2wdl_metafile_metadata
    Array[String]? custom_axes
    Boolean ignore_missing_samples
    Boolean ignore_pcoa_features
    String visualization
}

task qiime2_emperor_plot {

    input {
        File pcoa
        Array[File] q2wdl_metafile_metadata
        Array[String]? custom_axes
        Boolean ignore_missing_samples = false
        Boolean ignore_pcoa_features = false
        String visualization
    }

    qiime2_emperor_plot_params task_params = object {
        pcoa: pcoa,
        q2wdl_metafile_metadata: q2wdl_metafile_metadata,
        custom_axes: custom_axes,
        ignore_missing_samples: ignore_missing_samples,
        ignore_pcoa_features: ignore_pcoa_features,
        visualization: visualization
    }

    command {
        q2dataflow q2wdl run emperor plot ~{write_json(task_params)}
    }

    output {
        File visualization_file = "~{visualization}"
    }

}


workflow wkflw_qiime2_emperor_plot {
input {
        File pcoa
        Array[File] q2wdl_metafile_metadata
        Array[String]? custom_axes
        Boolean ignore_missing_samples = false
        Boolean ignore_pcoa_features = false
        String visualization
    }

    call qiime2_emperor_plot {
        input: pcoa=pcoa, q2wdl_metafile_metadata=q2wdl_metafile_metadata, custom_axes=custom_axes, ignore_missing_samples=ignore_missing_samples, ignore_pcoa_features=ignore_pcoa_features, visualization=visualization
    }

}
