# 
# Copyright (c) 2024, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This template was automatically generated by:
#     q2dataflow wdl (version: 0.2.0)
# for:
#     qiime2 (version: 2024.2.0)
# 


version 1.0

struct qiime2_diversity_pcoa_biplot_params {
    File pcoa
    File features
    String biplot
}

task qiime2_diversity_pcoa_biplot {

    input {
        File pcoa
        File features
        String biplot
    }

    qiime2_diversity_pcoa_biplot_params task_params = object {
        pcoa: pcoa,
        features: features,
        biplot: biplot
    }

    command {
        q2dataflow wdl run diversity pcoa_biplot ~{write_json(task_params)}
    }

    output {
        File biplot_file = "~{biplot}"
    }

}


workflow wkflw_qiime2_diversity_pcoa_biplot {
input {
        File pcoa
        File features
        String biplot
    }

    call qiime2_diversity_pcoa_biplot {
        input: pcoa=pcoa, features=features, biplot=biplot
    }

}
