# 
# Copyright (c) 2024, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This template was automatically generated by:
#     q2dataflow wdl (version: 0.2.0)
# for:
#     qiime2 (version: 2024.2.0)
# 


version 1.0

struct qiime2_diversity_core_metrics_params {
    File table
    Int sampling_depth
    Array[File] q2wdl_metafile_metadata
    Boolean with_replacement
    Int n_jobs
    Boolean ignore_missing_samples
    String rarefied_table
    String observed_features_vector
    String shannon_vector
    String evenness_vector
    String jaccard_distance_matrix
    String bray_curtis_distance_matrix
    String jaccard_pcoa_results
    String bray_curtis_pcoa_results
    String jaccard_emperor
    String bray_curtis_emperor
}

task qiime2_diversity_core_metrics {

    input {
        File table
        Int sampling_depth
        Array[File] q2wdl_metafile_metadata
        Boolean with_replacement = false
        Int n_jobs = 1
        Boolean ignore_missing_samples = false
        String rarefied_table
        String observed_features_vector
        String shannon_vector
        String evenness_vector
        String jaccard_distance_matrix
        String bray_curtis_distance_matrix
        String jaccard_pcoa_results
        String bray_curtis_pcoa_results
        String jaccard_emperor
        String bray_curtis_emperor
    }

    qiime2_diversity_core_metrics_params task_params = object {
        table: table,
        sampling_depth: sampling_depth,
        q2wdl_metafile_metadata: q2wdl_metafile_metadata,
        with_replacement: with_replacement,
        n_jobs: n_jobs,
        ignore_missing_samples: ignore_missing_samples,
        rarefied_table: rarefied_table,
        observed_features_vector: observed_features_vector,
        shannon_vector: shannon_vector,
        evenness_vector: evenness_vector,
        jaccard_distance_matrix: jaccard_distance_matrix,
        bray_curtis_distance_matrix: bray_curtis_distance_matrix,
        jaccard_pcoa_results: jaccard_pcoa_results,
        bray_curtis_pcoa_results: bray_curtis_pcoa_results,
        jaccard_emperor: jaccard_emperor,
        bray_curtis_emperor: bray_curtis_emperor
    }

    command {
        q2dataflow wdl run diversity core_metrics ~{write_json(task_params)}
    }

    output {
        File rarefied_table_file = "~{rarefied_table}"
        File observed_features_vector_file = "~{observed_features_vector}"
        File shannon_vector_file = "~{shannon_vector}"
        File evenness_vector_file = "~{evenness_vector}"
        File jaccard_distance_matrix_file = "~{jaccard_distance_matrix}"
        File bray_curtis_distance_matrix_file = "~{bray_curtis_distance_matrix}"
        File jaccard_pcoa_results_file = "~{jaccard_pcoa_results}"
        File bray_curtis_pcoa_results_file = "~{bray_curtis_pcoa_results}"
        File jaccard_emperor_file = "~{jaccard_emperor}"
        File bray_curtis_emperor_file = "~{bray_curtis_emperor}"
    }

}


workflow wkflw_qiime2_diversity_core_metrics {
input {
        File table
        Int sampling_depth
        Array[File] q2wdl_metafile_metadata
        Boolean with_replacement = false
        Int n_jobs = 1
        Boolean ignore_missing_samples = false
        String rarefied_table
        String observed_features_vector
        String shannon_vector
        String evenness_vector
        String jaccard_distance_matrix
        String bray_curtis_distance_matrix
        String jaccard_pcoa_results
        String bray_curtis_pcoa_results
        String jaccard_emperor
        String bray_curtis_emperor
    }

    call qiime2_diversity_core_metrics {
        input: table=table, sampling_depth=sampling_depth, q2wdl_metafile_metadata=q2wdl_metafile_metadata, with_replacement=with_replacement, n_jobs=n_jobs, ignore_missing_samples=ignore_missing_samples, rarefied_table=rarefied_table, observed_features_vector=observed_features_vector, shannon_vector=shannon_vector, evenness_vector=evenness_vector, jaccard_distance_matrix=jaccard_distance_matrix, bray_curtis_distance_matrix=bray_curtis_distance_matrix, jaccard_pcoa_results=jaccard_pcoa_results, bray_curtis_pcoa_results=bray_curtis_pcoa_results, jaccard_emperor=jaccard_emperor, bray_curtis_emperor=bray_curtis_emperor
    }

}
