# 
# Copyright (c) 2024, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This template was automatically generated by:
#     q2dataflow wdl (version: 0.2.0)
# for:
#     qiime2 (version: 2024.2.0)
# 


version 1.0

struct qiime2_diversity_alpha_rarefaction_params {
    File table
    File? phylogeny
    Int max_depth
    Array[String]? metrics
    Array[File]? q2wdl_metafile_metadata
    Int min_depth
    Int steps
    Int iterations
    String visualization
}

task qiime2_diversity_alpha_rarefaction {

    input {
        File table
        File? phylogeny
        Int max_depth
        Array[String]? metrics
        Array[File]? q2wdl_metafile_metadata
        Int min_depth = 1
        Int steps = 10
        Int iterations = 10
        String visualization
    }

    qiime2_diversity_alpha_rarefaction_params task_params = object {
        table: table,
        phylogeny: phylogeny,
        max_depth: max_depth,
        metrics: metrics,
        q2wdl_metafile_metadata: q2wdl_metafile_metadata,
        min_depth: min_depth,
        steps: steps,
        iterations: iterations,
        visualization: visualization
    }

    command {
        q2dataflow wdl run diversity alpha_rarefaction ~{write_json(task_params)}
    }

    output {
        File visualization_file = "~{visualization}"
    }

}


workflow wkflw_qiime2_diversity_alpha_rarefaction {
input {
        File table
        File? phylogeny
        Int max_depth
        Array[String]? metrics
        Array[File]? q2wdl_metafile_metadata
        Int min_depth = 1
        Int steps = 10
        Int iterations = 10
        String visualization
    }

    call qiime2_diversity_alpha_rarefaction {
        input: table=table, phylogeny=phylogeny, max_depth=max_depth, metrics=metrics, q2wdl_metafile_metadata=q2wdl_metafile_metadata, min_depth=min_depth, steps=steps, iterations=iterations, visualization=visualization
    }

}
