# 
# Copyright (c) 2024, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This template was automatically generated by:
#     q2dataflow wdl (version: 0.2.0)
# for:
#     qiime2 (version: 2024.2.0)
# 


version 1.0

struct qiime2_diversity_alpha_correlation_params {
    File alpha_diversity
    Array[File] q2wdl_metafile_metadata
    String method
    Boolean intersect_ids
    String visualization
}

task qiime2_diversity_alpha_correlation {

    input {
        File alpha_diversity
        Array[File] q2wdl_metafile_metadata
        String method = "spearman"
        Boolean intersect_ids = false
        String visualization
    }

    qiime2_diversity_alpha_correlation_params task_params = object {
        alpha_diversity: alpha_diversity,
        q2wdl_metafile_metadata: q2wdl_metafile_metadata,
        method: method,
        intersect_ids: intersect_ids,
        visualization: visualization
    }

    command {
        q2dataflow wdl run diversity alpha_correlation ~{write_json(task_params)}
    }

    output {
        File visualization_file = "~{visualization}"
    }

}


workflow wkflw_qiime2_diversity_alpha_correlation {
input {
        File alpha_diversity
        Array[File] q2wdl_metafile_metadata
        String method = "spearman"
        Boolean intersect_ids = false
        String visualization
    }

    call qiime2_diversity_alpha_correlation {
        input: alpha_diversity=alpha_diversity, q2wdl_metafile_metadata=q2wdl_metafile_metadata, method=method, intersect_ids=intersect_ids, visualization=visualization
    }

}
