# 
# Copyright (c) 2024, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This template was automatically generated by:
#     q2dataflow wdl (version: 0.2.0)
# for:
#     qiime2 (version: 2024.2.0)
# 


version 1.0

struct qiime2_diversity_adonis_params {
    File distance_matrix
    Array[File] q2wdl_metafile_metadata
    String formula
    Int permutations
    Int n_jobs
    String visualization
}

task qiime2_diversity_adonis {

    input {
        File distance_matrix
        Array[File] q2wdl_metafile_metadata
        String formula
        Int permutations = 999
        Int n_jobs = 1
        String visualization
    }

    qiime2_diversity_adonis_params task_params = object {
        distance_matrix: distance_matrix,
        q2wdl_metafile_metadata: q2wdl_metafile_metadata,
        formula: formula,
        permutations: permutations,
        n_jobs: n_jobs,
        visualization: visualization
    }

    command {
        q2dataflow wdl run diversity adonis ~{write_json(task_params)}
    }

    output {
        File visualization_file = "~{visualization}"
    }

}


workflow wkflw_qiime2_diversity_adonis {
input {
        File distance_matrix
        Array[File] q2wdl_metafile_metadata
        String formula
        Int permutations = 999
        Int n_jobs = 1
        String visualization
    }

    call qiime2_diversity_adonis {
        input: distance_matrix=distance_matrix, q2wdl_metafile_metadata=q2wdl_metafile_metadata, formula=formula, permutations=permutations, n_jobs=n_jobs, visualization=visualization
    }

}
