# 
# Copyright (c) 2024, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This template was automatically generated by:
#     q2dataflow wdl (version: 0.2.0)
# for:
#     qiime2 (version: 2024.2.0)
# 


version 1.0

struct qiime2_diversity_partial_procrustes_params {
    File reference
    File other
    String pairing
    File q2wdl_metafile_pairing
    Int dimensions
    String transformed
}

task qiime2_diversity_partial_procrustes {

    input {
        File reference
        File other
        String pairing
        File q2wdl_metafile_pairing
        Int dimensions = 5
        String transformed
    }

    qiime2_diversity_partial_procrustes_params task_params = object {
        reference: reference,
        other: other,
        pairing: pairing,
        q2wdl_metafile_pairing: q2wdl_metafile_pairing,
        dimensions: dimensions,
        transformed: transformed
    }

    command {
        q2dataflow wdl run diversity partial_procrustes ~{write_json(task_params)}
    }

    output {
        File transformed_file = "~{transformed}"
    }

}


workflow wkflw_qiime2_diversity_partial_procrustes {
input {
        File reference
        File other
        String pairing
        File q2wdl_metafile_pairing
        Int dimensions = 5
        String transformed
    }

    call qiime2_diversity_partial_procrustes {
        input: reference=reference, other=other, pairing=pairing, q2wdl_metafile_pairing=q2wdl_metafile_pairing, dimensions=dimensions, transformed=transformed
    }

}
