# 
# Copyright (c) 2024, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This template was automatically generated by:
#     q2dataflow wdl (version: 0.2.0)
# for:
#     qiime2 (version: 2024.2.0)
# 


version 1.0

struct qiime2_diversity_umap_params {
    File distance_matrix
    Int number_of_dimensions
    Int n_neighbors
    Float min_dist
    Int? random_state
    String umap
}

task qiime2_diversity_umap {

    input {
        File distance_matrix
        Int number_of_dimensions = 2
        Int n_neighbors = 15
        Float min_dist = 0.4
        Int? random_state
        String umap
    }

    qiime2_diversity_umap_params task_params = object {
        distance_matrix: distance_matrix,
        number_of_dimensions: number_of_dimensions,
        n_neighbors: n_neighbors,
        min_dist: min_dist,
        random_state: random_state,
        umap: umap
    }

    command {
        q2dataflow wdl run diversity umap ~{write_json(task_params)}
    }

    output {
        File umap_file = "~{umap}"
    }

}


workflow wkflw_qiime2_diversity_umap {
input {
        File distance_matrix
        Int number_of_dimensions = 2
        Int n_neighbors = 15
        Float min_dist = 0.4
        Int? random_state
        String umap
    }

    call qiime2_diversity_umap {
        input: distance_matrix=distance_matrix, number_of_dimensions=number_of_dimensions, n_neighbors=n_neighbors, min_dist=min_dist, random_state=random_state, umap=umap
    }

}
