# 
# Copyright (c) 2024, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This template was automatically generated by:
#     q2dataflow wdl (version: 0.2.0)
# for:
#     qiime2 (version: 2024.2.0)
# 


version 1.0

struct qiime2_diversity_tsne_params {
    File distance_matrix
    Int number_of_dimensions
    Float perplexity
    Int n_iter
    Float learning_rate
    Float early_exaggeration
    Int? random_state
    String tsne
}

task qiime2_diversity_tsne {

    input {
        File distance_matrix
        Int number_of_dimensions = 2
        Float perplexity = 25.0
        Int n_iter = 1000
        Float learning_rate = 200.0
        Float early_exaggeration = 12.0
        Int? random_state
        String tsne
    }

    qiime2_diversity_tsne_params task_params = object {
        distance_matrix: distance_matrix,
        number_of_dimensions: number_of_dimensions,
        perplexity: perplexity,
        n_iter: n_iter,
        learning_rate: learning_rate,
        early_exaggeration: early_exaggeration,
        random_state: random_state,
        tsne: tsne
    }

    command {
        q2dataflow wdl run diversity tsne ~{write_json(task_params)}
    }

    output {
        File tsne_file = "~{tsne}"
    }

}


workflow wkflw_qiime2_diversity_tsne {
input {
        File distance_matrix
        Int number_of_dimensions = 2
        Float perplexity = 25.0
        Int n_iter = 1000
        Float learning_rate = 200.0
        Float early_exaggeration = 12.0
        Int? random_state
        String tsne
    }

    call qiime2_diversity_tsne {
        input: distance_matrix=distance_matrix, number_of_dimensions=number_of_dimensions, perplexity=perplexity, n_iter=n_iter, learning_rate=learning_rate, early_exaggeration=early_exaggeration, random_state=random_state, tsne=tsne
    }

}
