# 
# Copyright (c) 2024, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This template was automatically generated by:
#     q2dataflow wdl (version: 0.2.0)
# for:
#     qiime2 (version: 2024.2.0)
# 


version 1.0

struct qiime2_diversity_filter_distance_matrix_params {
    File distance_matrix
    Array[File] q2wdl_metafile_metadata
    String? where
    Boolean exclude_ids
    String filtered_distance_matrix
}

task qiime2_diversity_filter_distance_matrix {

    input {
        File distance_matrix
        Array[File] q2wdl_metafile_metadata
        String? where
        Boolean exclude_ids = false
        String filtered_distance_matrix
    }

    qiime2_diversity_filter_distance_matrix_params task_params = object {
        distance_matrix: distance_matrix,
        q2wdl_metafile_metadata: q2wdl_metafile_metadata,
        where: where,
        exclude_ids: exclude_ids,
        filtered_distance_matrix: filtered_distance_matrix
    }

    command {
        q2dataflow wdl run diversity filter_distance_matrix ~{write_json(task_params)}
    }

    output {
        File filtered_distance_matrix_file = "~{filtered_distance_matrix}"
    }

}


workflow wkflw_qiime2_diversity_filter_distance_matrix {
input {
        File distance_matrix
        Array[File] q2wdl_metafile_metadata
        String? where
        Boolean exclude_ids = false
        String filtered_distance_matrix
    }

    call qiime2_diversity_filter_distance_matrix {
        input: distance_matrix=distance_matrix, q2wdl_metafile_metadata=q2wdl_metafile_metadata, where=where, exclude_ids=exclude_ids, filtered_distance_matrix=filtered_distance_matrix
    }

}
