# 
# Copyright (c) 2023, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This tool was automatically generated by:
#     q2wdl (version: 0.1.0)
# for:
#     qiime2 (version: 2023.2.0)
# 


version 1.0

struct qiime2_quality_control_bowtie2_build_params {
    File sequences
    Int n_threads
    String database
}

task qiime2_quality_control_bowtie2_build {

    input {
        File sequences
        Int n_threads = 1
        String database
    }

    qiime2_quality_control_bowtie2_build_params task_params = object {
        sequences: sequences,
        n_threads: n_threads,
        database: database
    }

    command {
        q2dataflow q2wdl run quality_control bowtie2_build ~{write_json(task_params)}
    }

    output {
        File database_file = "~{database}"
    }

}


workflow wkflw_qiime2_quality_control_bowtie2_build {
input {
        File sequences
        Int n_threads = 1
        String database
    }

    call qiime2_quality_control_bowtie2_build {
        input: sequences=sequences, n_threads=n_threads, database=database
    }

}
