# 
# Copyright (c) 2023, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This tool was automatically generated by:
#     q2wdl (version: 0.1.0)
# for:
#     qiime2 (version: 2023.2.0)
# 


version 1.0

struct qiime2_quality_control_evaluate_taxonomy_params {
    File expected_taxa
    File observed_taxa
    File? feature_table
    Int depth
    String palette
    Boolean require_exp_ids
    Boolean require_obs_ids
    String? sample_id
    String visualization
}

task qiime2_quality_control_evaluate_taxonomy {

    input {
        File expected_taxa
        File observed_taxa
        File? feature_table
        Int depth
        String palette = "Set1"
        Boolean require_exp_ids = true
        Boolean require_obs_ids = true
        String? sample_id
        String visualization
    }

    qiime2_quality_control_evaluate_taxonomy_params task_params = object {
        expected_taxa: expected_taxa,
        observed_taxa: observed_taxa,
        feature_table: feature_table,
        depth: depth,
        palette: palette,
        require_exp_ids: require_exp_ids,
        require_obs_ids: require_obs_ids,
        sample_id: sample_id,
        visualization: visualization
    }

    command {
        q2dataflow q2wdl run quality_control evaluate_taxonomy ~{write_json(task_params)}
    }

    output {
        File visualization_file = "~{visualization}"
    }

}


workflow wkflw_qiime2_quality_control_evaluate_taxonomy {
input {
        File expected_taxa
        File observed_taxa
        File? feature_table
        Int depth
        String palette = "Set1"
        Boolean require_exp_ids = true
        Boolean require_obs_ids = true
        String? sample_id
        String visualization
    }

    call qiime2_quality_control_evaluate_taxonomy {
        input: expected_taxa=expected_taxa, observed_taxa=observed_taxa, feature_table=feature_table, depth=depth, palette=palette, require_exp_ids=require_exp_ids, require_obs_ids=require_obs_ids, sample_id=sample_id, visualization=visualization
    }

}
