# 
# Copyright (c) 2023, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This tool was automatically generated by:
#     q2wdl (version: 0.1.0)
# for:
#     qiime2 (version: 2023.2.0)
# 


version 1.0

struct qiime2_demux_subsample_single_params {
    File sequences
    Float fraction
    String subsampled_sequences
}

task qiime2_demux_subsample_single {

    input {
        File sequences
        Float fraction
        String subsampled_sequences
    }

    qiime2_demux_subsample_single_params task_params = object {
        sequences: sequences,
        fraction: fraction,
        subsampled_sequences: subsampled_sequences
    }

    command {
        q2dataflow q2wdl run demux subsample_single ~{write_json(task_params)}
    }

    output {
        File subsampled_sequences_file = "~{subsampled_sequences}"
    }

}


workflow wkflw_qiime2_demux_subsample_single {
input {
        File sequences
        Float fraction
        String subsampled_sequences
    }

    call qiime2_demux_subsample_single {
        input: sequences=sequences, fraction=fraction, subsampled_sequences=subsampled_sequences
    }

}
