# 
# Copyright (c) 2023, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This tool was automatically generated by:
#     q2wdl (version: 0.1.0)
# for:
#     qiime2 (version: 2023.2.0)
# 


version 1.0

struct qiime2_demux_filter_samples_params {
    File demux
    Array[File] q2wdl_metafile_metadata
    String? where
    Boolean exclude_ids
    String filtered_demux
}

task qiime2_demux_filter_samples {

    input {
        File demux
        Array[File] q2wdl_metafile_metadata
        String? where
        Boolean exclude_ids = false
        String filtered_demux
    }

    qiime2_demux_filter_samples_params task_params = object {
        demux: demux,
        q2wdl_metafile_metadata: q2wdl_metafile_metadata,
        where: where,
        exclude_ids: exclude_ids,
        filtered_demux: filtered_demux
    }

    command {
        q2dataflow q2wdl run demux filter_samples ~{write_json(task_params)}
    }

    output {
        File filtered_demux_file = "~{filtered_demux}"
    }

}


workflow wkflw_qiime2_demux_filter_samples {
input {
        File demux
        Array[File] q2wdl_metafile_metadata
        String? where
        Boolean exclude_ids = false
        String filtered_demux
    }

    call qiime2_demux_filter_samples {
        input: demux=demux, q2wdl_metafile_metadata=q2wdl_metafile_metadata, where=where, exclude_ids=exclude_ids, filtered_demux=filtered_demux
    }

}
