# 
# Copyright (c) 2023, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This tool was automatically generated by:
#     q2wdl (version: 0.1.0)
# for:
#     qiime2 (version: 2023.2.0)
# 


version 1.0

struct qiime2_vsearch_cluster_features_closed_reference_params {
    File sequences
    File table
    File reference_sequences
    Float perc_identity
    String strand
    Int threads
    String clustered_table
    String clustered_sequences
    String unmatched_sequences
}

task qiime2_vsearch_cluster_features_closed_reference {

    input {
        File sequences
        File table
        File reference_sequences
        Float perc_identity
        String strand = "plus"
        Int threads = 1
        String clustered_table
        String clustered_sequences
        String unmatched_sequences
    }

    qiime2_vsearch_cluster_features_closed_reference_params task_params = object {
        sequences: sequences,
        table: table,
        reference_sequences: reference_sequences,
        perc_identity: perc_identity,
        strand: strand,
        threads: threads,
        clustered_table: clustered_table,
        clustered_sequences: clustered_sequences,
        unmatched_sequences: unmatched_sequences
    }

    command {
        q2dataflow q2wdl run vsearch cluster_features_closed_reference ~{write_json(task_params)}
    }

    output {
        File clustered_table_file = "~{clustered_table}"
        File clustered_sequences_file = "~{clustered_sequences}"
        File unmatched_sequences_file = "~{unmatched_sequences}"
    }

}


workflow wkflw_qiime2_vsearch_cluster_features_closed_reference {
input {
        File sequences
        File table
        File reference_sequences
        Float perc_identity
        String strand = "plus"
        Int threads = 1
        String clustered_table
        String clustered_sequences
        String unmatched_sequences
    }

    call qiime2_vsearch_cluster_features_closed_reference {
        input: sequences=sequences, table=table, reference_sequences=reference_sequences, perc_identity=perc_identity, strand=strand, threads=threads, clustered_table=clustered_table, clustered_sequences=clustered_sequences, unmatched_sequences=unmatched_sequences
    }

}
