# 
# Copyright (c) 2023, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This tool was automatically generated by:
#     q2wdl (version: 0.1.0)
# for:
#     qiime2 (version: 2023.2.0)
# 


version 1.0

struct qiime2_vsearch_uchime_ref_params {
    File sequences
    File table
    File reference_sequences
    Float dn
    Int mindiffs
    Float mindiv
    Float minh
    Float xn
    Int threads
    String chimeras
    String nonchimeras
    String stats
}

task qiime2_vsearch_uchime_ref {

    input {
        File sequences
        File table
        File reference_sequences
        Float dn = 1.4
        Int mindiffs = 3
        Float mindiv = 0.8
        Float minh = 0.28
        Float xn = 8.0
        Int threads = 1
        String chimeras
        String nonchimeras
        String stats
    }

    qiime2_vsearch_uchime_ref_params task_params = object {
        sequences: sequences,
        table: table,
        reference_sequences: reference_sequences,
        dn: dn,
        mindiffs: mindiffs,
        mindiv: mindiv,
        minh: minh,
        xn: xn,
        threads: threads,
        chimeras: chimeras,
        nonchimeras: nonchimeras,
        stats: stats
    }

    command {
        q2dataflow q2wdl run vsearch uchime_ref ~{write_json(task_params)}
    }

    output {
        File chimeras_file = "~{chimeras}"
        File nonchimeras_file = "~{nonchimeras}"
        File stats_file = "~{stats}"
    }

}


workflow wkflw_qiime2_vsearch_uchime_ref {
input {
        File sequences
        File table
        File reference_sequences
        Float dn = 1.4
        Int mindiffs = 3
        Float mindiv = 0.8
        Float minh = 0.28
        Float xn = 8.0
        Int threads = 1
        String chimeras
        String nonchimeras
        String stats
    }

    call qiime2_vsearch_uchime_ref {
        input: sequences=sequences, table=table, reference_sequences=reference_sequences, dn=dn, mindiffs=mindiffs, mindiv=mindiv, minh=minh, xn=xn, threads=threads, chimeras=chimeras, nonchimeras=nonchimeras, stats=stats
    }

}
