# 
# Copyright (c) 2023, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This tool was automatically generated by:
#     q2wdl (version: 0.1.0)
# for:
#     qiime2 (version: 2023.2.0)
# 


version 1.0

struct qiime2_vsearch_dereplicate_sequences_params {
    File sequences
    Boolean derep_prefix
    Int min_seq_length
    Int min_unique_size
    String dereplicated_table
    String dereplicated_sequences
}

task qiime2_vsearch_dereplicate_sequences {

    input {
        File sequences
        Boolean derep_prefix = false
        Int min_seq_length = 1
        Int min_unique_size = 1
        String dereplicated_table
        String dereplicated_sequences
    }

    qiime2_vsearch_dereplicate_sequences_params task_params = object {
        sequences: sequences,
        derep_prefix: derep_prefix,
        min_seq_length: min_seq_length,
        min_unique_size: min_unique_size,
        dereplicated_table: dereplicated_table,
        dereplicated_sequences: dereplicated_sequences
    }

    command {
        q2dataflow q2wdl run vsearch dereplicate_sequences ~{write_json(task_params)}
    }

    output {
        File dereplicated_table_file = "~{dereplicated_table}"
        File dereplicated_sequences_file = "~{dereplicated_sequences}"
    }

}


workflow wkflw_qiime2_vsearch_dereplicate_sequences {
input {
        File sequences
        Boolean derep_prefix = false
        Int min_seq_length = 1
        Int min_unique_size = 1
        String dereplicated_table
        String dereplicated_sequences
    }

    call qiime2_vsearch_dereplicate_sequences {
        input: sequences=sequences, derep_prefix=derep_prefix, min_seq_length=min_seq_length, min_unique_size=min_unique_size, dereplicated_table=dereplicated_table, dereplicated_sequences=dereplicated_sequences
    }

}
