# 
# Copyright (c) 2024, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This template was automatically generated by:
#     q2dataflow wdl (version: 0.2.0)
# for:
#     qiime2 (version: 2024.2.0)
# 


version 1.0

struct qiime2_rescript_get_ncbi_genomes_params {
    String taxon
    String assembly_source
    Array[String] assembly_levels
    Boolean only_reference
    Boolean tax_exact_match
    Int page_size
    String genome_assemblies
    String loci
    String proteins
    String taxonomies
}

task qiime2_rescript_get_ncbi_genomes {

    input {
        String taxon
        String assembly_source = "refseq"
        Array[String] assembly_levels = ['complete_genome']
        Boolean only_reference = true
        Boolean tax_exact_match = false
        Int page_size = 20
        String genome_assemblies
        String loci
        String proteins
        String taxonomies
    }

    qiime2_rescript_get_ncbi_genomes_params task_params = object {
        taxon: taxon,
        assembly_source: assembly_source,
        assembly_levels: assembly_levels,
        only_reference: only_reference,
        tax_exact_match: tax_exact_match,
        page_size: page_size,
        genome_assemblies: genome_assemblies,
        loci: loci,
        proteins: proteins,
        taxonomies: taxonomies
    }

    command {
        q2dataflow wdl run rescript get_ncbi_genomes ~{write_json(task_params)}
    }

    output {
        File genome_assemblies_file = "~{genome_assemblies}"
        File loci_file = "~{loci}"
        File proteins_file = "~{proteins}"
        File taxonomies_file = "~{taxonomies}"
    }

}


workflow wkflw_qiime2_rescript_get_ncbi_genomes {
input {
        String taxon
        String assembly_source = "refseq"
        Array[String] assembly_levels = ['complete_genome']
        Boolean only_reference = true
        Boolean tax_exact_match = false
        Int page_size = 20
        String genome_assemblies
        String loci
        String proteins
        String taxonomies
    }

    call qiime2_rescript_get_ncbi_genomes {
        input: taxon=taxon, assembly_source=assembly_source, assembly_levels=assembly_levels, only_reference=only_reference, tax_exact_match=tax_exact_match, page_size=page_size, genome_assemblies=genome_assemblies, loci=loci, proteins=proteins, taxonomies=taxonomies
    }

}
