# 
# Copyright (c) 2024, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This template was automatically generated by:
#     q2dataflow wdl (version: 0.2.0)
# for:
#     qiime2 (version: 2024.2.0)
# 


version 1.0

struct qiime2_rescript_evaluate_taxonomy_params {
    Array[File] taxonomies
    Array[String]? labels
    String? rank_handle_regex
    String taxonomy_stats
}

task qiime2_rescript_evaluate_taxonomy {

    input {
        Array[File] taxonomies
        Array[String]? labels
        String? rank_handle_regex
        String taxonomy_stats
    }

    qiime2_rescript_evaluate_taxonomy_params task_params = object {
        taxonomies: taxonomies,
        labels: labels,
        rank_handle_regex: rank_handle_regex,
        taxonomy_stats: taxonomy_stats
    }

    command {
        q2dataflow wdl run rescript evaluate_taxonomy ~{write_json(task_params)}
    }

    output {
        File taxonomy_stats_file = "~{taxonomy_stats}"
    }

}


workflow wkflw_qiime2_rescript_evaluate_taxonomy {
input {
        Array[File] taxonomies
        Array[String]? labels
        String? rank_handle_regex
        String taxonomy_stats
    }

    call qiime2_rescript_evaluate_taxonomy {
        input: taxonomies=taxonomies, labels=labels, rank_handle_regex=rank_handle_regex, taxonomy_stats=taxonomy_stats
    }

}
