# 
# Copyright (c) 2024, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This template was automatically generated by:
#     q2dataflow wdl (version: 0.2.0)
# for:
#     qiime2 (version: 2024.2.0)
# 


version 1.0

struct qiime2_rescript_evaluate_classifications_params {
    Array[File] expected_taxonomies
    Array[File] observed_taxonomies
    Array[String]? labels
    String evaluation
}

task qiime2_rescript_evaluate_classifications {

    input {
        Array[File] expected_taxonomies
        Array[File] observed_taxonomies
        Array[String]? labels
        String evaluation
    }

    qiime2_rescript_evaluate_classifications_params task_params = object {
        expected_taxonomies: expected_taxonomies,
        observed_taxonomies: observed_taxonomies,
        labels: labels,
        evaluation: evaluation
    }

    command {
        q2dataflow wdl run rescript evaluate_classifications ~{write_json(task_params)}
    }

    output {
        File evaluation_file = "~{evaluation}"
    }

}


workflow wkflw_qiime2_rescript_evaluate_classifications {
input {
        Array[File] expected_taxonomies
        Array[File] observed_taxonomies
        Array[String]? labels
        String evaluation
    }

    call qiime2_rescript_evaluate_classifications {
        input: expected_taxonomies=expected_taxonomies, observed_taxonomies=observed_taxonomies, labels=labels, evaluation=evaluation
    }

}
