# 
# Copyright (c) 2024, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This template was automatically generated by:
#     q2dataflow wdl (version: 0.2.0)
# for:
#     qiime2 (version: 2024.2.0)
# 


version 1.0

struct qiime2_rescript_subsample_fasta_params {
    File sequences
    Float subsample_size
    Int random_seed
    String sample_sequences
}

task qiime2_rescript_subsample_fasta {

    input {
        File sequences
        Float subsample_size = 0.1
        Int random_seed = 1
        String sample_sequences
    }

    qiime2_rescript_subsample_fasta_params task_params = object {
        sequences: sequences,
        subsample_size: subsample_size,
        random_seed: random_seed,
        sample_sequences: sample_sequences
    }

    command {
        q2dataflow wdl run rescript subsample_fasta ~{write_json(task_params)}
    }

    output {
        File sample_sequences_file = "~{sample_sequences}"
    }

}


workflow wkflw_qiime2_rescript_subsample_fasta {
input {
        File sequences
        Float subsample_size = 0.1
        Int random_seed = 1
        String sample_sequences
    }

    call qiime2_rescript_subsample_fasta {
        input: sequences=sequences, subsample_size=subsample_size, random_seed=random_seed, sample_sequences=sample_sequences
    }

}
