# 
# Copyright (c) 2024, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This template was automatically generated by:
#     q2dataflow wdl (version: 0.2.0)
# for:
#     qiime2 (version: 2024.2.0)
# 


version 1.0

struct qiime2_rescript_trim_alignment_params {
    File aligned_sequences
    String? primer_fwd
    String? primer_rev
    Int? position_start
    Int? position_end
    String trimmed_sequences
}

task qiime2_rescript_trim_alignment {

    input {
        File aligned_sequences
        String? primer_fwd
        String? primer_rev
        Int? position_start
        Int? position_end
        String trimmed_sequences
    }

    qiime2_rescript_trim_alignment_params task_params = object {
        aligned_sequences: aligned_sequences,
        primer_fwd: primer_fwd,
        primer_rev: primer_rev,
        position_start: position_start,
        position_end: position_end,
        trimmed_sequences: trimmed_sequences
    }

    command {
        q2dataflow wdl run rescript trim_alignment ~{write_json(task_params)}
    }

    output {
        File trimmed_sequences_file = "~{trimmed_sequences}"
    }

}


workflow wkflw_qiime2_rescript_trim_alignment {
input {
        File aligned_sequences
        String? primer_fwd
        String? primer_rev
        Int? position_start
        Int? position_end
        String trimmed_sequences
    }

    call qiime2_rescript_trim_alignment {
        input: aligned_sequences=aligned_sequences, primer_fwd=primer_fwd, primer_rev=primer_rev, position_start=position_start, position_end=position_end, trimmed_sequences=trimmed_sequences
    }

}
