# 
# Copyright (c) 2024, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This template was automatically generated by:
#     q2dataflow wdl (version: 0.2.0)
# for:
#     qiime2 (version: 2024.2.0)
# 


version 1.0

struct qiime2_rescript_filter_taxa_params {
    File taxonomy
    Array[File]? q2wdl_metafile_ids_to_keep
    Array[String]? include
    Array[String]? exclude
    String filtered_taxonomy
}

task qiime2_rescript_filter_taxa {

    input {
        File taxonomy
        Array[File]? q2wdl_metafile_ids_to_keep
        Array[String]? include
        Array[String]? exclude
        String filtered_taxonomy
    }

    qiime2_rescript_filter_taxa_params task_params = object {
        taxonomy: taxonomy,
        q2wdl_metafile_ids_to_keep: q2wdl_metafile_ids_to_keep,
        include: include,
        exclude: exclude,
        filtered_taxonomy: filtered_taxonomy
    }

    command {
        q2dataflow wdl run rescript filter_taxa ~{write_json(task_params)}
    }

    output {
        File filtered_taxonomy_file = "~{filtered_taxonomy}"
    }

}


workflow wkflw_qiime2_rescript_filter_taxa {
input {
        File taxonomy
        Array[File]? q2wdl_metafile_ids_to_keep
        Array[String]? include
        Array[String]? exclude
        String filtered_taxonomy
    }

    call qiime2_rescript_filter_taxa {
        input: taxonomy=taxonomy, q2wdl_metafile_ids_to_keep=q2wdl_metafile_ids_to_keep, include=include, exclude=exclude, filtered_taxonomy=filtered_taxonomy
    }

}
