# 
# Copyright (c) 2024, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This template was automatically generated by:
#     q2dataflow wdl (version: 0.2.0)
# for:
#     qiime2 (version: 2024.2.0)
# 


version 1.0

struct qiime2_rescript_evaluate_seqs_params {
    Array[File] sequences
    Array[String]? labels
    Array[Int]? kmer_lengths
    Float subsample_kmers
    String palette
    String visualization
}

task qiime2_rescript_evaluate_seqs {

    input {
        Array[File] sequences
        Array[String]? labels
        Array[Int]? kmer_lengths
        Float subsample_kmers = 1.0
        String palette = "viridis"
        String visualization
    }

    qiime2_rescript_evaluate_seqs_params task_params = object {
        sequences: sequences,
        labels: labels,
        kmer_lengths: kmer_lengths,
        subsample_kmers: subsample_kmers,
        palette: palette,
        visualization: visualization
    }

    command {
        q2dataflow wdl run rescript evaluate_seqs ~{write_json(task_params)}
    }

    output {
        File visualization_file = "~{visualization}"
    }

}


workflow wkflw_qiime2_rescript_evaluate_seqs {
input {
        Array[File] sequences
        Array[String]? labels
        Array[Int]? kmer_lengths
        Float subsample_kmers = 1.0
        String palette = "viridis"
        String visualization
    }

    call qiime2_rescript_evaluate_seqs {
        input: sequences=sequences, labels=labels, kmer_lengths=kmer_lengths, subsample_kmers=subsample_kmers, palette=palette, visualization=visualization
    }

}
