# 
# Copyright (c) 2024, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This template was automatically generated by:
#     q2dataflow wdl (version: 0.2.0)
# for:
#     qiime2 (version: 2024.2.0)
# 


version 1.0

struct qiime2_rescript_cull_seqs_params {
    File sequences
    Int num_degenerates
    Int homopolymer_length
    Int n_jobs
    String clean_sequences
}

task qiime2_rescript_cull_seqs {

    input {
        File sequences
        Int num_degenerates = 5
        Int homopolymer_length = 8
        Int n_jobs = 1
        String clean_sequences
    }

    qiime2_rescript_cull_seqs_params task_params = object {
        sequences: sequences,
        num_degenerates: num_degenerates,
        homopolymer_length: homopolymer_length,
        n_jobs: n_jobs,
        clean_sequences: clean_sequences
    }

    command {
        q2dataflow wdl run rescript cull_seqs ~{write_json(task_params)}
    }

    output {
        File clean_sequences_file = "~{clean_sequences}"
    }

}


workflow wkflw_qiime2_rescript_cull_seqs {
input {
        File sequences
        Int num_degenerates = 5
        Int homopolymer_length = 8
        Int n_jobs = 1
        String clean_sequences
    }

    call qiime2_rescript_cull_seqs {
        input: sequences=sequences, num_degenerates=num_degenerates, homopolymer_length=homopolymer_length, n_jobs=n_jobs, clean_sequences=clean_sequences
    }

}
