# 
# Copyright (c) 2024, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This template was automatically generated by:
#     q2dataflow wdl (version: 0.2.0)
# for:
#     qiime2 (version: 2024.2.0)
# 


version 1.0

struct qiime2_rescript_get_unite_data_params {
    String version
    String taxon_group
    String cluster_id
    Boolean singletons
    String taxonomy
    String sequences
}

task qiime2_rescript_get_unite_data {

    input {
        String version = "9.0"
        String taxon_group = "eukaryotes"
        String cluster_id = "99"
        Boolean singletons = false
        String taxonomy
        String sequences
    }

    qiime2_rescript_get_unite_data_params task_params = object {
        version: version,
        taxon_group: taxon_group,
        cluster_id: cluster_id,
        singletons: singletons,
        taxonomy: taxonomy,
        sequences: sequences
    }

    command {
        q2dataflow wdl run rescript get_unite_data ~{write_json(task_params)}
    }

    output {
        File taxonomy_file = "~{taxonomy}"
        File sequences_file = "~{sequences}"
    }

}


workflow wkflw_qiime2_rescript_get_unite_data {
input {
        String version = "9.0"
        String taxon_group = "eukaryotes"
        String cluster_id = "99"
        Boolean singletons = false
        String taxonomy
        String sequences
    }

    call qiime2_rescript_get_unite_data {
        input: version=version, taxon_group=taxon_group, cluster_id=cluster_id, singletons=singletons, taxonomy=taxonomy, sequences=sequences
    }

}
