# 
# Copyright (c) 2024, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This template was automatically generated by:
#     q2dataflow wdl (version: 0.2.0)
# for:
#     qiime2 (version: 2024.2.0)
# 


version 1.0

struct qiime2_rescript_reverse_transcribe_params {
    File rna_sequences
    String dna_sequences
}

task qiime2_rescript_reverse_transcribe {

    input {
        File rna_sequences
        String dna_sequences
    }

    qiime2_rescript_reverse_transcribe_params task_params = object {
        rna_sequences: rna_sequences,
        dna_sequences: dna_sequences
    }

    command {
        q2dataflow wdl run rescript reverse_transcribe ~{write_json(task_params)}
    }

    output {
        File dna_sequences_file = "~{dna_sequences}"
    }

}


workflow wkflw_qiime2_rescript_reverse_transcribe {
input {
        File rna_sequences
        String dna_sequences
    }

    call qiime2_rescript_reverse_transcribe {
        input: rna_sequences=rna_sequences, dna_sequences=dna_sequences
    }

}
