# 
# Copyright (c) 2024, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This template was automatically generated by:
#     q2dataflow wdl (version: 0.2.0)
# for:
#     qiime2 (version: 2024.2.0)
# 


version 1.0

struct qiime2_rescript_parse_silva_taxonomy_params {
    File taxonomy_tree
    File taxonomy_map
    File taxonomy_ranks
    Boolean rank_propagation
    Array[String]? ranks
    Boolean include_species_labels
    String taxonomy
}

task qiime2_rescript_parse_silva_taxonomy {

    input {
        File taxonomy_tree
        File taxonomy_map
        File taxonomy_ranks
        Boolean rank_propagation = true
        Array[String]? ranks
        Boolean include_species_labels = false
        String taxonomy
    }

    qiime2_rescript_parse_silva_taxonomy_params task_params = object {
        taxonomy_tree: taxonomy_tree,
        taxonomy_map: taxonomy_map,
        taxonomy_ranks: taxonomy_ranks,
        rank_propagation: rank_propagation,
        ranks: ranks,
        include_species_labels: include_species_labels,
        taxonomy: taxonomy
    }

    command {
        q2dataflow wdl run rescript parse_silva_taxonomy ~{write_json(task_params)}
    }

    output {
        File taxonomy_file = "~{taxonomy}"
    }

}


workflow wkflw_qiime2_rescript_parse_silva_taxonomy {
input {
        File taxonomy_tree
        File taxonomy_map
        File taxonomy_ranks
        Boolean rank_propagation = true
        Array[String]? ranks
        Boolean include_species_labels = false
        String taxonomy
    }

    call qiime2_rescript_parse_silva_taxonomy {
        input: taxonomy_tree=taxonomy_tree, taxonomy_map=taxonomy_map, taxonomy_ranks=taxonomy_ranks, rank_propagation=rank_propagation, ranks=ranks, include_species_labels=include_species_labels, taxonomy=taxonomy
    }

}
