# 
# Copyright (c) 2024, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This template was automatically generated by:
#     q2dataflow wdl (version: 0.2.0)
# for:
#     qiime2 (version: 2024.2.0)
# 


version 1.0

struct qiime2_rescript_get_gtdb_data_params {
    String version
    String domain
    String db_type
    String gtdb_taxonomy
    String gtdb_sequences
}

task qiime2_rescript_get_gtdb_data {

    input {
        String version = "214.1"
        String domain = "Both"
        String db_type = "SpeciesReps"
        String gtdb_taxonomy
        String gtdb_sequences
    }

    qiime2_rescript_get_gtdb_data_params task_params = object {
        version: version,
        domain: domain,
        db_type: db_type,
        gtdb_taxonomy: gtdb_taxonomy,
        gtdb_sequences: gtdb_sequences
    }

    command {
        q2dataflow wdl run rescript get_gtdb_data ~{write_json(task_params)}
    }

    output {
        File gtdb_taxonomy_file = "~{gtdb_taxonomy}"
        File gtdb_sequences_file = "~{gtdb_sequences}"
    }

}


workflow wkflw_qiime2_rescript_get_gtdb_data {
input {
        String version = "214.1"
        String domain = "Both"
        String db_type = "SpeciesReps"
        String gtdb_taxonomy
        String gtdb_sequences
    }

    call qiime2_rescript_get_gtdb_data {
        input: version=version, domain=domain, db_type=db_type, gtdb_taxonomy=gtdb_taxonomy, gtdb_sequences=gtdb_sequences
    }

}
