# 
# Copyright (c) 2024, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This template was automatically generated by:
#     q2dataflow wdl (version: 0.2.0)
# for:
#     qiime2 (version: 2024.2.0)
# 


version 1.0

struct qiime2_rescript_get_ncbi_data_protein_params {
    String? query
    Array[File]? q2wdl_metafile_accession_ids
    Array[String]? ranks
    Boolean rank_propagation
    String? logging_level
    Int n_jobs
    String sequences
    String taxonomy
}

task qiime2_rescript_get_ncbi_data_protein {

    input {
        String? query
        Array[File]? q2wdl_metafile_accession_ids
        Array[String]? ranks
        Boolean rank_propagation = true
        String? logging_level
        Int n_jobs = 1
        String sequences
        String taxonomy
    }

    qiime2_rescript_get_ncbi_data_protein_params task_params = object {
        query: query,
        q2wdl_metafile_accession_ids: q2wdl_metafile_accession_ids,
        ranks: ranks,
        rank_propagation: rank_propagation,
        logging_level: logging_level,
        n_jobs: n_jobs,
        sequences: sequences,
        taxonomy: taxonomy
    }

    command {
        q2dataflow wdl run rescript get_ncbi_data_protein ~{write_json(task_params)}
    }

    output {
        File sequences_file = "~{sequences}"
        File taxonomy_file = "~{taxonomy}"
    }

}


workflow wkflw_qiime2_rescript_get_ncbi_data_protein {
input {
        String? query
        Array[File]? q2wdl_metafile_accession_ids
        Array[String]? ranks
        Boolean rank_propagation = true
        String? logging_level
        Int n_jobs = 1
        String sequences
        String taxonomy
    }

    call qiime2_rescript_get_ncbi_data_protein {
        input: query=query, q2wdl_metafile_accession_ids=q2wdl_metafile_accession_ids, ranks=ranks, rank_propagation=rank_propagation, logging_level=logging_level, n_jobs=n_jobs, sequences=sequences, taxonomy=taxonomy
    }

}
