# 
# Copyright (c) 2024, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This template was automatically generated by:
#     q2dataflow wdl (version: 0.2.0)
# for:
#     qiime2 (version: 2024.2.0)
# 


version 1.0

struct qiime2_rescript_degap_seqs_params {
    File aligned_sequences
    Int min_length
    String degapped_sequences
}

task qiime2_rescript_degap_seqs {

    input {
        File aligned_sequences
        Int min_length = 1
        String degapped_sequences
    }

    qiime2_rescript_degap_seqs_params task_params = object {
        aligned_sequences: aligned_sequences,
        min_length: min_length,
        degapped_sequences: degapped_sequences
    }

    command {
        q2dataflow wdl run rescript degap_seqs ~{write_json(task_params)}
    }

    output {
        File degapped_sequences_file = "~{degapped_sequences}"
    }

}


workflow wkflw_qiime2_rescript_degap_seqs {
input {
        File aligned_sequences
        Int min_length = 1
        String degapped_sequences
    }

    call qiime2_rescript_degap_seqs {
        input: aligned_sequences=aligned_sequences, min_length=min_length, degapped_sequences=degapped_sequences
    }

}
