# 
# Copyright (c) 2024, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This template was automatically generated by:
#     q2dataflow wdl (version: 0.2.0)
# for:
#     qiime2 (version: 2024.2.0)
# 


version 1.0

struct qiime2_rescript_edit_taxonomy_params {
    File taxonomy
    String? replacement_map
    File? q2wdl_metafile_replacement_map
    Array[String]? search_strings
    Array[String]? replacement_strings
    Boolean use_regex
    String edited_taxonomy
}

task qiime2_rescript_edit_taxonomy {

    input {
        File taxonomy
        String? replacement_map
        File? q2wdl_metafile_replacement_map
        Array[String]? search_strings
        Array[String]? replacement_strings
        Boolean use_regex = false
        String edited_taxonomy
    }

    qiime2_rescript_edit_taxonomy_params task_params = object {
        taxonomy: taxonomy,
        replacement_map: replacement_map,
        q2wdl_metafile_replacement_map: q2wdl_metafile_replacement_map,
        search_strings: search_strings,
        replacement_strings: replacement_strings,
        use_regex: use_regex,
        edited_taxonomy: edited_taxonomy
    }

    command {
        q2dataflow wdl run rescript edit_taxonomy ~{write_json(task_params)}
    }

    output {
        File edited_taxonomy_file = "~{edited_taxonomy}"
    }

}


workflow wkflw_qiime2_rescript_edit_taxonomy {
input {
        File taxonomy
        String? replacement_map
        File? q2wdl_metafile_replacement_map
        Array[String]? search_strings
        Array[String]? replacement_strings
        Boolean use_regex = false
        String edited_taxonomy
    }

    call qiime2_rescript_edit_taxonomy {
        input: taxonomy=taxonomy, replacement_map=replacement_map, q2wdl_metafile_replacement_map=q2wdl_metafile_replacement_map, search_strings=search_strings, replacement_strings=replacement_strings, use_regex=use_regex, edited_taxonomy=edited_taxonomy
    }

}
