# 
# Copyright (c) 2023, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This tool was automatically generated by:
#     q2wdl (version: 0.1.0)
# for:
#     qiime2 (version: 2023.2.0)
# 


version 1.0

struct qiime2_feature_table_group_params {
    File table
    String axis
    String metadata
    File q2wdl_metafile_metadata
    String mode
    String grouped_table
}

task qiime2_feature_table_group {

    input {
        File table
        String axis
        String metadata
        File q2wdl_metafile_metadata
        String mode
        String grouped_table
    }

    qiime2_feature_table_group_params task_params = object {
        table: table,
        axis: axis,
        metadata: metadata,
        q2wdl_metafile_metadata: q2wdl_metafile_metadata,
        mode: mode,
        grouped_table: grouped_table
    }

    command {
        q2dataflow q2wdl run feature_table group ~{write_json(task_params)}
    }

    output {
        File grouped_table_file = "~{grouped_table}"
    }

}


workflow wkflw_qiime2_feature_table_group {
input {
        File table
        String axis
        String metadata
        File q2wdl_metafile_metadata
        String mode
        String grouped_table
    }

    call qiime2_feature_table_group {
        input: table=table, axis=axis, metadata=metadata, q2wdl_metafile_metadata=q2wdl_metafile_metadata, mode=mode, grouped_table=grouped_table
    }

}
