# 
# Copyright (c) 2023, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This tool was automatically generated by:
#     q2wdl (version: 0.1.0)
# for:
#     qiime2 (version: 2023.2.0)
# 


version 1.0

struct qiime2_feature_table_heatmap_params {
    File table
    String? sample_metadata
    File? q2wdl_metafile_sample_metadata
    String? feature_metadata
    File? q2wdl_metafile_feature_metadata
    Boolean normalize
    String? title
    String metric
    String method
    String cluster
    String color_scheme
    String visualization
}

task qiime2_feature_table_heatmap {

    input {
        File table
        String? sample_metadata
        File? q2wdl_metafile_sample_metadata
        String? feature_metadata
        File? q2wdl_metafile_feature_metadata
        Boolean normalize = true
        String? title
        String metric = "euclidean"
        String method = "average"
        String cluster = "both"
        String color_scheme = "rocket"
        String visualization
    }

    qiime2_feature_table_heatmap_params task_params = object {
        table: table,
        sample_metadata: sample_metadata,
        q2wdl_metafile_sample_metadata: q2wdl_metafile_sample_metadata,
        feature_metadata: feature_metadata,
        q2wdl_metafile_feature_metadata: q2wdl_metafile_feature_metadata,
        normalize: normalize,
        title: title,
        metric: metric,
        method: method,
        cluster: cluster,
        color_scheme: color_scheme,
        visualization: visualization
    }

    command {
        q2dataflow q2wdl run feature_table heatmap ~{write_json(task_params)}
    }

    output {
        File visualization_file = "~{visualization}"
    }

}


workflow wkflw_qiime2_feature_table_heatmap {
input {
        File table
        String? sample_metadata
        File? q2wdl_metafile_sample_metadata
        String? feature_metadata
        File? q2wdl_metafile_feature_metadata
        Boolean normalize = true
        String? title
        String metric = "euclidean"
        String method = "average"
        String cluster = "both"
        String color_scheme = "rocket"
        String visualization
    }

    call qiime2_feature_table_heatmap {
        input: table=table, sample_metadata=sample_metadata, q2wdl_metafile_sample_metadata=q2wdl_metafile_sample_metadata, feature_metadata=feature_metadata, q2wdl_metafile_feature_metadata=q2wdl_metafile_feature_metadata, normalize=normalize, title=title, metric=metric, method=method, cluster=cluster, color_scheme=color_scheme, visualization=visualization
    }

}
