# 
# Copyright (c) 2024, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This template was automatically generated by:
#     q2dataflow wdl (version: 0.2.0)
# for:
#     qiime2 (version: 2024.2.0)
# 


version 1.0

struct qiime2_deblur_visualize_stats_params {
    File deblur_stats
    String visualization
}

task qiime2_deblur_visualize_stats {

    input {
        File deblur_stats
        String visualization
    }

    qiime2_deblur_visualize_stats_params task_params = object {
        deblur_stats: deblur_stats,
        visualization: visualization
    }

    command {
        q2dataflow wdl run deblur visualize_stats ~{write_json(task_params)}
    }

    output {
        File visualization_file = "~{visualization}"
    }

}


workflow wkflw_qiime2_deblur_visualize_stats {
input {
        File deblur_stats
        String visualization
    }

    call qiime2_deblur_visualize_stats {
        input: deblur_stats=deblur_stats, visualization=visualization
    }

}
