# 
# Copyright (c) 2024, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This template was automatically generated by:
#     q2dataflow wdl (version: 0.2.0)
# for:
#     qiime2 (version: 2024.2.0)
# 


version 1.0

struct qiime2_demux_partition_samples_paired_params {
    File demux
    Int? num_partitions
    String partitioned_demux
}

task qiime2_demux_partition_samples_paired {

    input {
        File demux
        Int? num_partitions
        String partitioned_demux
    }

    qiime2_demux_partition_samples_paired_params task_params = object {
        demux: demux,
        num_partitions: num_partitions,
        partitioned_demux: partitioned_demux
    }

    command {
        q2dataflow wdl run demux partition_samples_paired ~{write_json(task_params)}
    }

    

}


workflow wkflw_qiime2_demux_partition_samples_paired {
input {
        File demux
        Int? num_partitions
        String partitioned_demux
    }

    call qiime2_demux_partition_samples_paired {
        input: demux=demux, num_partitions=num_partitions, partitioned_demux=partitioned_demux
    }

}
