# 
# Copyright (c) 2024, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This template was automatically generated by:
#     q2dataflow wdl (version: 0.2.0)
# for:
#     qiime2 (version: 2024.2.0)
# 


version 1.0

struct qiime2_demux_emp_single_params {
    File seqs
    String barcodes
    File q2wdl_metafile_barcodes
    Boolean golay_error_correction
    Boolean rev_comp_barcodes
    Boolean rev_comp_mapping_barcodes
    Boolean ignore_description_mismatch
    String per_sample_sequences
    String error_correction_details
}

task qiime2_demux_emp_single {

    input {
        File seqs
        String barcodes
        File q2wdl_metafile_barcodes
        Boolean golay_error_correction = true
        Boolean rev_comp_barcodes = false
        Boolean rev_comp_mapping_barcodes = false
        Boolean ignore_description_mismatch = false
        String per_sample_sequences
        String error_correction_details
    }

    qiime2_demux_emp_single_params task_params = object {
        seqs: seqs,
        barcodes: barcodes,
        q2wdl_metafile_barcodes: q2wdl_metafile_barcodes,
        golay_error_correction: golay_error_correction,
        rev_comp_barcodes: rev_comp_barcodes,
        rev_comp_mapping_barcodes: rev_comp_mapping_barcodes,
        ignore_description_mismatch: ignore_description_mismatch,
        per_sample_sequences: per_sample_sequences,
        error_correction_details: error_correction_details
    }

    command {
        q2dataflow wdl run demux emp_single ~{write_json(task_params)}
    }

    output {
        File per_sample_sequences_file = "~{per_sample_sequences}"
        File error_correction_details_file = "~{error_correction_details}"
    }

}


workflow wkflw_qiime2_demux_emp_single {
input {
        File seqs
        String barcodes
        File q2wdl_metafile_barcodes
        Boolean golay_error_correction = true
        Boolean rev_comp_barcodes = false
        Boolean rev_comp_mapping_barcodes = false
        Boolean ignore_description_mismatch = false
        String per_sample_sequences
        String error_correction_details
    }

    call qiime2_demux_emp_single {
        input: seqs=seqs, barcodes=barcodes, q2wdl_metafile_barcodes=q2wdl_metafile_barcodes, golay_error_correction=golay_error_correction, rev_comp_barcodes=rev_comp_barcodes, rev_comp_mapping_barcodes=rev_comp_mapping_barcodes, ignore_description_mismatch=ignore_description_mismatch, per_sample_sequences=per_sample_sequences, error_correction_details=error_correction_details
    }

}
