# 
# Copyright (c) 2024, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This template was automatically generated by:
#     q2dataflow wdl (version: 0.2.0)
# for:
#     qiime2 (version: 2024.2.0)
# 


version 1.0

struct qiime2_demux_summarize_params {
    File data
    Int n
    String visualization
}

task qiime2_demux_summarize {

    input {
        File data
        Int n = 10000
        String visualization
    }

    qiime2_demux_summarize_params task_params = object {
        data: data,
        n: n,
        visualization: visualization
    }

    command {
        q2dataflow wdl run demux summarize ~{write_json(task_params)}
    }

    output {
        File visualization_file = "~{visualization}"
    }

}


workflow wkflw_qiime2_demux_summarize {
input {
        File data
        Int n = 10000
        String visualization
    }

    call qiime2_demux_summarize {
        input: data=data, n=n, visualization=visualization
    }

}
