# 
# Copyright (c) 2024, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This template was automatically generated by:
#     q2dataflow wdl (version: 0.2.0)
# for:
#     qiime2 (version: 2024.2.0)
# 


version 1.0

struct qiime2_demux_subsample_paired_params {
    File sequences
    Float fraction
    String subsampled_sequences
}

task qiime2_demux_subsample_paired {

    input {
        File sequences
        Float fraction
        String subsampled_sequences
    }

    qiime2_demux_subsample_paired_params task_params = object {
        sequences: sequences,
        fraction: fraction,
        subsampled_sequences: subsampled_sequences
    }

    command {
        q2dataflow wdl run demux subsample_paired ~{write_json(task_params)}
    }

    output {
        File subsampled_sequences_file = "~{subsampled_sequences}"
    }

}


workflow wkflw_qiime2_demux_subsample_paired {
input {
        File sequences
        Float fraction
        String subsampled_sequences
    }

    call qiime2_demux_subsample_paired {
        input: sequences=sequences, fraction=fraction, subsampled_sequences=subsampled_sequences
    }

}
