# 
# Copyright (c) 2024, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This template was automatically generated by:
#     q2dataflow wdl (version: 0.2.0)
# for:
#     qiime2 (version: 2024.2.0)
# 


version 1.0

struct qiime2_demux_tabulate_read_counts_params {
    Array[File] sequences
    String counts
}

task qiime2_demux_tabulate_read_counts {

    input {
        Array[File] sequences
        String counts
    }

    qiime2_demux_tabulate_read_counts_params task_params = object {
        sequences: sequences,
        counts: counts
    }

    command {
        q2dataflow wdl run demux tabulate_read_counts ~{write_json(task_params)}
    }

    output {
        File counts_file = "~{counts}"
    }

}


workflow wkflw_qiime2_demux_tabulate_read_counts {
input {
        Array[File] sequences
        String counts
    }

    call qiime2_demux_tabulate_read_counts {
        input: sequences=sequences, counts=counts
    }

}
