# 
# Copyright (c) 2024, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This template was automatically generated by:
#     q2dataflow wdl (version: 0.2.0)
# for:
#     qiime2 (version: 2024.2.0)
# 


version 1.0

struct qiime2_vsearch_cluster_features_de_novo_params {
    File sequences
    File table
    Float perc_identity
    String strand
    Int threads
    String clustered_table
    String clustered_sequences
}

task qiime2_vsearch_cluster_features_de_novo {

    input {
        File sequences
        File table
        Float perc_identity
        String strand = "plus"
        Int threads = 1
        String clustered_table
        String clustered_sequences
    }

    qiime2_vsearch_cluster_features_de_novo_params task_params = object {
        sequences: sequences,
        table: table,
        perc_identity: perc_identity,
        strand: strand,
        threads: threads,
        clustered_table: clustered_table,
        clustered_sequences: clustered_sequences
    }

    command {
        q2dataflow wdl run vsearch cluster_features_de_novo ~{write_json(task_params)}
    }

    output {
        File clustered_table_file = "~{clustered_table}"
        File clustered_sequences_file = "~{clustered_sequences}"
    }

}


workflow wkflw_qiime2_vsearch_cluster_features_de_novo {
input {
        File sequences
        File table
        Float perc_identity
        String strand = "plus"
        Int threads = 1
        String clustered_table
        String clustered_sequences
    }

    call qiime2_vsearch_cluster_features_de_novo {
        input: sequences=sequences, table=table, perc_identity=perc_identity, strand=strand, threads=threads, clustered_table=clustered_table, clustered_sequences=clustered_sequences
    }

}
