# 
# Copyright (c) 2023, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This tool was automatically generated by:
#     q2wdl (version: 0.1.0)
# for:
#     qiime2 (version: 2023.2.0)
# 


version 1.0

struct qiime2_alignment_mafft_add_params {
    File alignment
    File sequences
    String n_threads
    Boolean parttree
    Boolean addfragments
    String expanded_alignment
}

task qiime2_alignment_mafft_add {

    input {
        File alignment
        File sequences
        String n_threads = '1'
        Boolean parttree = false
        Boolean addfragments = false
        String expanded_alignment
    }

    qiime2_alignment_mafft_add_params task_params = object {
        alignment: alignment,
        sequences: sequences,
        n_threads: n_threads,
        parttree: parttree,
        addfragments: addfragments,
        expanded_alignment: expanded_alignment
    }

    command {
        q2dataflow q2wdl run alignment mafft_add ~{write_json(task_params)}
    }

    output {
        File expanded_alignment_file = "~{expanded_alignment}"
    }

}


workflow wkflw_qiime2_alignment_mafft_add {
input {
        File alignment
        File sequences
        String n_threads = '1'
        Boolean parttree = false
        Boolean addfragments = false
        String expanded_alignment
    }

    call qiime2_alignment_mafft_add {
        input: alignment=alignment, sequences=sequences, n_threads=n_threads, parttree=parttree, addfragments=addfragments, expanded_alignment=expanded_alignment
    }

}
