# 
# Copyright (c) 2024, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This template was automatically generated by:
#     q2dataflow wdl (version: 0.2.0)
# for:
#     qiime2 (version: 2024.2.0)
# 


version 1.0

struct qiime2_diversity_lib_faith_pd_params {
    File table
    File phylogeny
    Int threads
    String vector
}

task qiime2_diversity_lib_faith_pd {

    input {
        File table
        File phylogeny
        Int threads = 1
        String vector
    }

    qiime2_diversity_lib_faith_pd_params task_params = object {
        table: table,
        phylogeny: phylogeny,
        threads: threads,
        vector: vector
    }

    command {
        q2dataflow wdl run diversity_lib faith_pd ~{write_json(task_params)}
    }

    output {
        File vector_file = "~{vector}"
    }

}


workflow wkflw_qiime2_diversity_lib_faith_pd {
input {
        File table
        File phylogeny
        Int threads = 1
        String vector
    }

    call qiime2_diversity_lib_faith_pd {
        input: table=table, phylogeny=phylogeny, threads=threads, vector=vector
    }

}
