# 
# Copyright (c) 2024, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This template was automatically generated by:
#     q2dataflow wdl (version: 0.2.0)
# for:
#     qiime2 (version: 2024.2.0)
# 


version 1.0

struct qiime2_diversity_lib_alpha_passthrough_params {
    File table
    String metric
    String vector
}

task qiime2_diversity_lib_alpha_passthrough {

    input {
        File table
        String metric
        String vector
    }

    qiime2_diversity_lib_alpha_passthrough_params task_params = object {
        table: table,
        metric: metric,
        vector: vector
    }

    command {
        q2dataflow wdl run diversity_lib alpha_passthrough ~{write_json(task_params)}
    }

    output {
        File vector_file = "~{vector}"
    }

}


workflow wkflw_qiime2_diversity_lib_alpha_passthrough {
input {
        File table
        String metric
        String vector
    }

    call qiime2_diversity_lib_alpha_passthrough {
        input: table=table, metric=metric, vector=vector
    }

}
