# 
# Copyright (c) 2023, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This tool was automatically generated by:
#     q2wdl (version: 0.1.0)
# for:
#     qiime2 (version: 2023.2.0)
# 


version 1.0

struct qiime2_longitudinal_first_distances_params {
    File distance_matrix
    Array[File] q2wdl_metafile_metadata
    String state_column
    String individual_id_column
    Float? baseline
    String replicate_handling
    String first_distances
}

task qiime2_longitudinal_first_distances {

    input {
        File distance_matrix
        Array[File] q2wdl_metafile_metadata
        String state_column
        String individual_id_column
        Float? baseline
        String replicate_handling = "error"
        String first_distances
    }

    qiime2_longitudinal_first_distances_params task_params = object {
        distance_matrix: distance_matrix,
        q2wdl_metafile_metadata: q2wdl_metafile_metadata,
        state_column: state_column,
        individual_id_column: individual_id_column,
        baseline: baseline,
        replicate_handling: replicate_handling,
        first_distances: first_distances
    }

    command {
        q2dataflow q2wdl run longitudinal first_distances ~{write_json(task_params)}
    }

    output {
        File first_distances_file = "~{first_distances}"
    }

}


workflow wkflw_qiime2_longitudinal_first_distances {
input {
        File distance_matrix
        Array[File] q2wdl_metafile_metadata
        String state_column
        String individual_id_column
        Float? baseline
        String replicate_handling = "error"
        String first_distances
    }

    call qiime2_longitudinal_first_distances {
        input: distance_matrix=distance_matrix, q2wdl_metafile_metadata=q2wdl_metafile_metadata, state_column=state_column, individual_id_column=individual_id_column, baseline=baseline, replicate_handling=replicate_handling, first_distances=first_distances
    }

}
