# 
# Copyright (c) 2023, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This tool was automatically generated by:
#     q2wdl (version: 0.1.0)
# for:
#     qiime2 (version: 2023.2.0)
# 


version 1.0

struct qiime2_longitudinal_maturity_index_params {
    File table
    Array[File] q2wdl_metafile_metadata
    String state_column
    String group_by
    String control
    String? individual_id_column
    String estimator
    Int n_estimators
    Float test_size
    Float step
    Int cv
    Int? random_state
    Int n_jobs
    Boolean parameter_tuning
    Boolean optimize_feature_selection
    Boolean stratify
    String missing_samples
    Int feature_count
    String sample_estimator
    String feature_importance
    String predictions
    String model_summary
    String accuracy_results
    String maz_scores
    String clustermap
    String volatility_plots
}

task qiime2_longitudinal_maturity_index {

    input {
        File table
        Array[File] q2wdl_metafile_metadata
        String state_column
        String group_by
        String control
        String? individual_id_column
        String estimator = "RandomForestRegressor"
        Int n_estimators = 100
        Float test_size = 0.5
        Float step = 0.05
        Int cv = 5
        Int? random_state
        Int n_jobs = 1
        Boolean parameter_tuning = false
        Boolean optimize_feature_selection = false
        Boolean stratify = false
        String missing_samples = "error"
        Int feature_count = 50
        String sample_estimator
        String feature_importance
        String predictions
        String model_summary
        String accuracy_results
        String maz_scores
        String clustermap
        String volatility_plots
    }

    qiime2_longitudinal_maturity_index_params task_params = object {
        table: table,
        q2wdl_metafile_metadata: q2wdl_metafile_metadata,
        state_column: state_column,
        group_by: group_by,
        control: control,
        individual_id_column: individual_id_column,
        estimator: estimator,
        n_estimators: n_estimators,
        test_size: test_size,
        step: step,
        cv: cv,
        random_state: random_state,
        n_jobs: n_jobs,
        parameter_tuning: parameter_tuning,
        optimize_feature_selection: optimize_feature_selection,
        stratify: stratify,
        missing_samples: missing_samples,
        feature_count: feature_count,
        sample_estimator: sample_estimator,
        feature_importance: feature_importance,
        predictions: predictions,
        model_summary: model_summary,
        accuracy_results: accuracy_results,
        maz_scores: maz_scores,
        clustermap: clustermap,
        volatility_plots: volatility_plots
    }

    command {
        q2dataflow q2wdl run longitudinal maturity_index ~{write_json(task_params)}
    }

    output {
        File sample_estimator_file = "~{sample_estimator}"
        File feature_importance_file = "~{feature_importance}"
        File predictions_file = "~{predictions}"
        File model_summary_file = "~{model_summary}"
        File accuracy_results_file = "~{accuracy_results}"
        File maz_scores_file = "~{maz_scores}"
        File clustermap_file = "~{clustermap}"
        File volatility_plots_file = "~{volatility_plots}"
    }

}


workflow wkflw_qiime2_longitudinal_maturity_index {
input {
        File table
        Array[File] q2wdl_metafile_metadata
        String state_column
        String group_by
        String control
        String? individual_id_column
        String estimator = "RandomForestRegressor"
        Int n_estimators = 100
        Float test_size = 0.5
        Float step = 0.05
        Int cv = 5
        Int? random_state
        Int n_jobs = 1
        Boolean parameter_tuning = false
        Boolean optimize_feature_selection = false
        Boolean stratify = false
        String missing_samples = "error"
        Int feature_count = 50
        String sample_estimator
        String feature_importance
        String predictions
        String model_summary
        String accuracy_results
        String maz_scores
        String clustermap
        String volatility_plots
    }

    call qiime2_longitudinal_maturity_index {
        input: table=table, q2wdl_metafile_metadata=q2wdl_metafile_metadata, state_column=state_column, group_by=group_by, control=control, individual_id_column=individual_id_column, estimator=estimator, n_estimators=n_estimators, test_size=test_size, step=step, cv=cv, random_state=random_state, n_jobs=n_jobs, parameter_tuning=parameter_tuning, optimize_feature_selection=optimize_feature_selection, stratify=stratify, missing_samples=missing_samples, feature_count=feature_count, sample_estimator=sample_estimator, feature_importance=feature_importance, predictions=predictions, model_summary=model_summary, accuracy_results=accuracy_results, maz_scores=maz_scores, clustermap=clustermap, volatility_plots=volatility_plots
    }

}
