# 
# Copyright (c) 2023, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This tool was automatically generated by:
#     q2wdl (version: 0.1.0)
# for:
#     qiime2 (version: 2023.2.0)
# 


version 1.0

struct qiime2_longitudinal_pairwise_differences_params {
    File? table
    Array[File] q2wdl_metafile_metadata
    String metric
    String state_column
    String state_1
    String state_2
    String individual_id_column
    String? group_column
    Boolean parametric
    String palette
    String replicate_handling
    String visualization
}

task qiime2_longitudinal_pairwise_differences {

    input {
        File? table
        Array[File] q2wdl_metafile_metadata
        String metric
        String state_column
        String state_1
        String state_2
        String individual_id_column
        String? group_column
        Boolean parametric = false
        String palette = "Set1"
        String replicate_handling = "error"
        String visualization
    }

    qiime2_longitudinal_pairwise_differences_params task_params = object {
        table: table,
        q2wdl_metafile_metadata: q2wdl_metafile_metadata,
        metric: metric,
        state_column: state_column,
        state_1: state_1,
        state_2: state_2,
        individual_id_column: individual_id_column,
        group_column: group_column,
        parametric: parametric,
        palette: palette,
        replicate_handling: replicate_handling,
        visualization: visualization
    }

    command {
        q2dataflow q2wdl run longitudinal pairwise_differences ~{write_json(task_params)}
    }

    output {
        File visualization_file = "~{visualization}"
    }

}


workflow wkflw_qiime2_longitudinal_pairwise_differences {
input {
        File? table
        Array[File] q2wdl_metafile_metadata
        String metric
        String state_column
        String state_1
        String state_2
        String individual_id_column
        String? group_column
        Boolean parametric = false
        String palette = "Set1"
        String replicate_handling = "error"
        String visualization
    }

    call qiime2_longitudinal_pairwise_differences {
        input: table=table, q2wdl_metafile_metadata=q2wdl_metafile_metadata, metric=metric, state_column=state_column, state_1=state_1, state_2=state_2, individual_id_column=individual_id_column, group_column=group_column, parametric=parametric, palette=palette, replicate_handling=replicate_handling, visualization=visualization
    }

}
