# 
# Copyright (c) 2023, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This tool was automatically generated by:
#     q2wdl (version: 0.1.0)
# for:
#     qiime2 (version: 2023.2.0)
# 


version 1.0

struct qiime2_longitudinal_anova_params {
    Array[File] q2wdl_metafile_metadata
    String formula
    String sstype
    String visualization
}

task qiime2_longitudinal_anova {

    input {
        Array[File] q2wdl_metafile_metadata
        String formula
        String sstype = "II"
        String visualization
    }

    qiime2_longitudinal_anova_params task_params = object {
        q2wdl_metafile_metadata: q2wdl_metafile_metadata,
        formula: formula,
        sstype: sstype,
        visualization: visualization
    }

    command {
        q2dataflow q2wdl run longitudinal anova ~{write_json(task_params)}
    }

    output {
        File visualization_file = "~{visualization}"
    }

}


workflow wkflw_qiime2_longitudinal_anova {
input {
        Array[File] q2wdl_metafile_metadata
        String formula
        String sstype = "II"
        String visualization
    }

    call qiime2_longitudinal_anova {
        input: q2wdl_metafile_metadata=q2wdl_metafile_metadata, formula=formula, sstype=sstype, visualization=visualization
    }

}
