# 
# Copyright (c) 2023, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This tool was automatically generated by:
#     q2wdl (version: 0.1.0)
# for:
#     qiime2 (version: 2023.2.0)
# 


version 1.0

struct qiime2_longitudinal_plot_feature_volatility_params {
    File table
    File importances
    Array[File] q2wdl_metafile_metadata
    String state_column
    String? individual_id_column
    String? default_group_column
    String yscale
    String? importance_threshold
    String feature_count
    String missing_samples
    String visualization
}

task qiime2_longitudinal_plot_feature_volatility {

    input {
        File table
        File importances
        Array[File] q2wdl_metafile_metadata
        String state_column
        String? individual_id_column
        String? default_group_column
        String yscale = "linear"
        String? importance_threshold
        String feature_count = '100'
        String missing_samples = "error"
        String visualization
    }

    qiime2_longitudinal_plot_feature_volatility_params task_params = object {
        table: table,
        importances: importances,
        q2wdl_metafile_metadata: q2wdl_metafile_metadata,
        state_column: state_column,
        individual_id_column: individual_id_column,
        default_group_column: default_group_column,
        yscale: yscale,
        importance_threshold: importance_threshold,
        feature_count: feature_count,
        missing_samples: missing_samples,
        visualization: visualization
    }

    command {
        q2dataflow q2wdl run longitudinal plot_feature_volatility ~{write_json(task_params)}
    }

    output {
        File visualization_file = "~{visualization}"
    }

}


workflow wkflw_qiime2_longitudinal_plot_feature_volatility {
input {
        File table
        File importances
        Array[File] q2wdl_metafile_metadata
        String state_column
        String? individual_id_column
        String? default_group_column
        String yscale = "linear"
        String? importance_threshold
        String feature_count = '100'
        String missing_samples = "error"
        String visualization
    }

    call qiime2_longitudinal_plot_feature_volatility {
        input: table=table, importances=importances, q2wdl_metafile_metadata=q2wdl_metafile_metadata, state_column=state_column, individual_id_column=individual_id_column, default_group_column=default_group_column, yscale=yscale, importance_threshold=importance_threshold, feature_count=feature_count, missing_samples=missing_samples, visualization=visualization
    }

}
