# 
# Copyright (c) 2023, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This tool was automatically generated by:
#     q2wdl (version: 0.1.0)
# for:
#     qiime2 (version: 2023.2.0)
# 


version 1.0

struct qiime2_composition_tabulate_params {
    File data
    String visualization
}

task qiime2_composition_tabulate {

    input {
        File data
        String visualization
    }

    qiime2_composition_tabulate_params task_params = object {
        data: data,
        visualization: visualization
    }

    command {
        q2dataflow q2wdl run composition tabulate ~{write_json(task_params)}
    }

    output {
        File visualization_file = "~{visualization}"
    }

}


workflow wkflw_qiime2_composition_tabulate {
input {
        File data
        String visualization
    }

    call qiime2_composition_tabulate {
        input: data=data, visualization=visualization
    }

}
