# 
# Copyright (c) 2023, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This tool was automatically generated by:
#     q2wdl (version: 0.1.0)
# for:
#     qiime2 (version: 2023.2.0)
# 


version 1.0

struct qiime2_composition_da_barplot_params {
    File data
    String effect_size_label
    String feature_id_label
    String error_label
    String significance_label
    Float significance_threshold
    Float effect_size_threshold
    Array[File]? q2wdl_metafile_feature_ids
    String visualization
}

task qiime2_composition_da_barplot {

    input {
        File data
        String effect_size_label = "lfc"
        String feature_id_label = "id"
        String error_label = "se"
        String significance_label = "q_val"
        Float significance_threshold = 1.0
        Float effect_size_threshold = 0.0
        Array[File]? q2wdl_metafile_feature_ids
        String visualization
    }

    qiime2_composition_da_barplot_params task_params = object {
        data: data,
        effect_size_label: effect_size_label,
        feature_id_label: feature_id_label,
        error_label: error_label,
        significance_label: significance_label,
        significance_threshold: significance_threshold,
        effect_size_threshold: effect_size_threshold,
        q2wdl_metafile_feature_ids: q2wdl_metafile_feature_ids,
        visualization: visualization
    }

    command {
        q2dataflow q2wdl run composition da_barplot ~{write_json(task_params)}
    }

    output {
        File visualization_file = "~{visualization}"
    }

}


workflow wkflw_qiime2_composition_da_barplot {
input {
        File data
        String effect_size_label = "lfc"
        String feature_id_label = "id"
        String error_label = "se"
        String significance_label = "q_val"
        Float significance_threshold = 1.0
        Float effect_size_threshold = 0.0
        Array[File]? q2wdl_metafile_feature_ids
        String visualization
    }

    call qiime2_composition_da_barplot {
        input: data=data, effect_size_label=effect_size_label, feature_id_label=feature_id_label, error_label=error_label, significance_label=significance_label, significance_threshold=significance_threshold, effect_size_threshold=effect_size_threshold, q2wdl_metafile_feature_ids=q2wdl_metafile_feature_ids, visualization=visualization
    }

}
