# 
# Copyright (c) 2024, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This template was automatically generated by:
#     q2dataflow wdl (version: 0.2.0)
# for:
#     qiime2 (version: 2024.2.0)
# 


version 1.0

struct qiime2_feature_classifier_makeblastdb_params {
    File sequences
    String database
}

task qiime2_feature_classifier_makeblastdb {

    input {
        File sequences
        String database
    }

    qiime2_feature_classifier_makeblastdb_params task_params = object {
        sequences: sequences,
        database: database
    }

    command {
        q2dataflow wdl run feature_classifier makeblastdb ~{write_json(task_params)}
    }

    output {
        File database_file = "~{database}"
    }

}


workflow wkflw_qiime2_feature_classifier_makeblastdb {
input {
        File sequences
        String database
    }

    call qiime2_feature_classifier_makeblastdb {
        input: sequences=sequences, database=database
    }

}
