# 
# Copyright (c) 2024, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This template was automatically generated by:
#     q2dataflow wdl (version: 0.2.0)
# for:
#     qiime2 (version: 2024.2.0)
# 


version 1.0

struct qiime2_feature_classifier_blast_params {
    File query
    File? reference_reads
    File? blastdb
    Int maxaccepts
    Float perc_identity
    Float query_cov
    String strand
    Float evalue
    Boolean output_no_hits
    Int num_threads
    String search_results
}

task qiime2_feature_classifier_blast {

    input {
        File query
        File? reference_reads
        File? blastdb
        Int maxaccepts = 10
        Float perc_identity = 0.8
        Float query_cov = 0.8
        String strand = "both"
        Float evalue = 0.001
        Boolean output_no_hits = true
        Int num_threads = 1
        String search_results
    }

    qiime2_feature_classifier_blast_params task_params = object {
        query: query,
        reference_reads: reference_reads,
        blastdb: blastdb,
        maxaccepts: maxaccepts,
        perc_identity: perc_identity,
        query_cov: query_cov,
        strand: strand,
        evalue: evalue,
        output_no_hits: output_no_hits,
        num_threads: num_threads,
        search_results: search_results
    }

    command {
        q2dataflow wdl run feature_classifier blast ~{write_json(task_params)}
    }

    output {
        File search_results_file = "~{search_results}"
    }

}


workflow wkflw_qiime2_feature_classifier_blast {
input {
        File query
        File? reference_reads
        File? blastdb
        Int maxaccepts = 10
        Float perc_identity = 0.8
        Float query_cov = 0.8
        String strand = "both"
        Float evalue = 0.001
        Boolean output_no_hits = true
        Int num_threads = 1
        String search_results
    }

    call qiime2_feature_classifier_blast {
        input: query=query, reference_reads=reference_reads, blastdb=blastdb, maxaccepts=maxaccepts, perc_identity=perc_identity, query_cov=query_cov, strand=strand, evalue=evalue, output_no_hits=output_no_hits, num_threads=num_threads, search_results=search_results
    }

}
