# 
# Copyright (c) 2024, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This template was automatically generated by:
#     q2dataflow wdl (version: 0.2.0)
# for:
#     qiime2 (version: 2024.2.0)
# 


version 1.0

struct qiime2_feature_classifier_find_consensus_annotation_params {
    File search_results
    File reference_taxonomy
    Float min_consensus
    String unassignable_label
    String consensus_taxonomy
}

task qiime2_feature_classifier_find_consensus_annotation {

    input {
        File search_results
        File reference_taxonomy
        Float min_consensus = 0.51
        String unassignable_label = "Unassigned"
        String consensus_taxonomy
    }

    qiime2_feature_classifier_find_consensus_annotation_params task_params = object {
        search_results: search_results,
        reference_taxonomy: reference_taxonomy,
        min_consensus: min_consensus,
        unassignable_label: unassignable_label,
        consensus_taxonomy: consensus_taxonomy
    }

    command {
        q2dataflow wdl run feature_classifier find_consensus_annotation ~{write_json(task_params)}
    }

    output {
        File consensus_taxonomy_file = "~{consensus_taxonomy}"
    }

}


workflow wkflw_qiime2_feature_classifier_find_consensus_annotation {
input {
        File search_results
        File reference_taxonomy
        Float min_consensus = 0.51
        String unassignable_label = "Unassigned"
        String consensus_taxonomy
    }

    call qiime2_feature_classifier_find_consensus_annotation {
        input: search_results=search_results, reference_taxonomy=reference_taxonomy, min_consensus=min_consensus, unassignable_label=unassignable_label, consensus_taxonomy=consensus_taxonomy
    }

}
