# 
# Copyright (c) 2024, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This template was automatically generated by:
#     q2dataflow wdl (version: 0.2.0)
# for:
#     qiime2 (version: 2024.2.0)
# 


version 1.0

struct qiime2_sample_classifier_metatable_params {
    File? table
    Array[File] q2wdl_metafile_metadata
    String missing_samples
    String missing_values
    Boolean drop_all_unique
    String converted_table
}

task qiime2_sample_classifier_metatable {

    input {
        File? table
        Array[File] q2wdl_metafile_metadata
        String missing_samples = "ignore"
        String missing_values = "error"
        Boolean drop_all_unique = false
        String converted_table
    }

    qiime2_sample_classifier_metatable_params task_params = object {
        table: table,
        q2wdl_metafile_metadata: q2wdl_metafile_metadata,
        missing_samples: missing_samples,
        missing_values: missing_values,
        drop_all_unique: drop_all_unique,
        converted_table: converted_table
    }

    command {
        q2dataflow wdl run sample_classifier metatable ~{write_json(task_params)}
    }

    output {
        File converted_table_file = "~{converted_table}"
    }

}


workflow wkflw_qiime2_sample_classifier_metatable {
input {
        File? table
        Array[File] q2wdl_metafile_metadata
        String missing_samples = "ignore"
        String missing_values = "error"
        Boolean drop_all_unique = false
        String converted_table
    }

    call qiime2_sample_classifier_metatable {
        input: table=table, q2wdl_metafile_metadata=q2wdl_metafile_metadata, missing_samples=missing_samples, missing_values=missing_values, drop_all_unique=drop_all_unique, converted_table=converted_table
    }

}
