# 
# Copyright (c) 2024, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This template was automatically generated by:
#     q2dataflow wdl (version: 0.2.0)
# for:
#     qiime2 (version: 2024.2.0)
# 


version 1.0

struct qiime2_sample_classifier_predict_regression_params {
    File table
    File sample_estimator
    Int n_jobs
    String predictions
}

task qiime2_sample_classifier_predict_regression {

    input {
        File table
        File sample_estimator
        Int n_jobs = 1
        String predictions
    }

    qiime2_sample_classifier_predict_regression_params task_params = object {
        table: table,
        sample_estimator: sample_estimator,
        n_jobs: n_jobs,
        predictions: predictions
    }

    command {
        q2dataflow wdl run sample_classifier predict_regression ~{write_json(task_params)}
    }

    output {
        File predictions_file = "~{predictions}"
    }

}


workflow wkflw_qiime2_sample_classifier_predict_regression {
input {
        File table
        File sample_estimator
        Int n_jobs = 1
        String predictions
    }

    call qiime2_sample_classifier_predict_regression {
        input: table=table, sample_estimator=sample_estimator, n_jobs=n_jobs, predictions=predictions
    }

}
