# 
# Copyright (c) 2024, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This template was automatically generated by:
#     q2dataflow wdl (version: 0.2.0)
# for:
#     qiime2 (version: 2024.2.0)
# 


version 1.0

struct qiime2_sample_classifier_split_table_params {
    File table
    String metadata
    File q2wdl_metafile_metadata
    Float test_size
    Int? random_state
    Boolean stratify
    String missing_samples
    String training_table
    String test_table
    String training_targets
    String test_targets
}

task qiime2_sample_classifier_split_table {

    input {
        File table
        String metadata
        File q2wdl_metafile_metadata
        Float test_size = 0.2
        Int? random_state
        Boolean stratify = true
        String missing_samples = "error"
        String training_table
        String test_table
        String training_targets
        String test_targets
    }

    qiime2_sample_classifier_split_table_params task_params = object {
        table: table,
        metadata: metadata,
        q2wdl_metafile_metadata: q2wdl_metafile_metadata,
        test_size: test_size,
        random_state: random_state,
        stratify: stratify,
        missing_samples: missing_samples,
        training_table: training_table,
        test_table: test_table,
        training_targets: training_targets,
        test_targets: test_targets
    }

    command {
        q2dataflow wdl run sample_classifier split_table ~{write_json(task_params)}
    }

    output {
        File training_table_file = "~{training_table}"
        File test_table_file = "~{test_table}"
        File training_targets_file = "~{training_targets}"
        File test_targets_file = "~{test_targets}"
    }

}


workflow wkflw_qiime2_sample_classifier_split_table {
input {
        File table
        String metadata
        File q2wdl_metafile_metadata
        Float test_size = 0.2
        Int? random_state
        Boolean stratify = true
        String missing_samples = "error"
        String training_table
        String test_table
        String training_targets
        String test_targets
    }

    call qiime2_sample_classifier_split_table {
        input: table=table, metadata=metadata, q2wdl_metafile_metadata=q2wdl_metafile_metadata, test_size=test_size, random_state=random_state, stratify=stratify, missing_samples=missing_samples, training_table=training_table, test_table=test_table, training_targets=training_targets, test_targets=test_targets
    }

}
