# 
# Copyright (c) 2024, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This template was automatically generated by:
#     q2dataflow wdl (version: 0.2.0)
# for:
#     qiime2 (version: 2024.2.0)
# 


version 1.0

struct qiime2_sample_classifier_classify_samples_ncv_params {
    File table
    String metadata
    File q2wdl_metafile_metadata
    Int cv
    Int? random_state
    Int n_jobs
    Int n_estimators
    String estimator
    Boolean parameter_tuning
    String missing_samples
    String predictions
    String feature_importance
    String probabilities
}

task qiime2_sample_classifier_classify_samples_ncv {

    input {
        File table
        String metadata
        File q2wdl_metafile_metadata
        Int cv = 5
        Int? random_state
        Int n_jobs = 1
        Int n_estimators = 100
        String estimator = "RandomForestClassifier"
        Boolean parameter_tuning = false
        String missing_samples = "error"
        String predictions
        String feature_importance
        String probabilities
    }

    qiime2_sample_classifier_classify_samples_ncv_params task_params = object {
        table: table,
        metadata: metadata,
        q2wdl_metafile_metadata: q2wdl_metafile_metadata,
        cv: cv,
        random_state: random_state,
        n_jobs: n_jobs,
        n_estimators: n_estimators,
        estimator: estimator,
        parameter_tuning: parameter_tuning,
        missing_samples: missing_samples,
        predictions: predictions,
        feature_importance: feature_importance,
        probabilities: probabilities
    }

    command {
        q2dataflow wdl run sample_classifier classify_samples_ncv ~{write_json(task_params)}
    }

    output {
        File predictions_file = "~{predictions}"
        File feature_importance_file = "~{feature_importance}"
        File probabilities_file = "~{probabilities}"
    }

}


workflow wkflw_qiime2_sample_classifier_classify_samples_ncv {
input {
        File table
        String metadata
        File q2wdl_metafile_metadata
        Int cv = 5
        Int? random_state
        Int n_jobs = 1
        Int n_estimators = 100
        String estimator = "RandomForestClassifier"
        Boolean parameter_tuning = false
        String missing_samples = "error"
        String predictions
        String feature_importance
        String probabilities
    }

    call qiime2_sample_classifier_classify_samples_ncv {
        input: table=table, metadata=metadata, q2wdl_metafile_metadata=q2wdl_metafile_metadata, cv=cv, random_state=random_state, n_jobs=n_jobs, n_estimators=n_estimators, estimator=estimator, parameter_tuning=parameter_tuning, missing_samples=missing_samples, predictions=predictions, feature_importance=feature_importance, probabilities=probabilities
    }

}
