# 
# Copyright (c) 2024, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This template was automatically generated by:
#     q2dataflow wdl (version: 0.2.0)
# for:
#     qiime2 (version: 2024.2.0)
# 


version 1.0

struct qiime2_cutadapt_demux_paired_params {
    File seqs
    String forward_barcodes
    File q2wdl_metafile_forward_barcodes
    String? reverse_barcodes
    File? q2wdl_metafile_reverse_barcodes
    Int forward_cut
    Int reverse_cut
    Boolean anchor_forward_barcode
    Boolean anchor_reverse_barcode
    Float error_rate
    Int batch_size
    Int minimum_length
    Boolean mixed_orientation
    Int cores
    String per_sample_sequences
    String untrimmed_sequences
}

task qiime2_cutadapt_demux_paired {

    input {
        File seqs
        String forward_barcodes
        File q2wdl_metafile_forward_barcodes
        String? reverse_barcodes
        File? q2wdl_metafile_reverse_barcodes
        Int forward_cut = 0
        Int reverse_cut = 0
        Boolean anchor_forward_barcode = false
        Boolean anchor_reverse_barcode = false
        Float error_rate = 0.1
        Int batch_size = 0
        Int minimum_length = 1
        Boolean mixed_orientation = false
        Int cores = 1
        String per_sample_sequences
        String untrimmed_sequences
    }

    qiime2_cutadapt_demux_paired_params task_params = object {
        seqs: seqs,
        forward_barcodes: forward_barcodes,
        q2wdl_metafile_forward_barcodes: q2wdl_metafile_forward_barcodes,
        reverse_barcodes: reverse_barcodes,
        q2wdl_metafile_reverse_barcodes: q2wdl_metafile_reverse_barcodes,
        forward_cut: forward_cut,
        reverse_cut: reverse_cut,
        anchor_forward_barcode: anchor_forward_barcode,
        anchor_reverse_barcode: anchor_reverse_barcode,
        error_rate: error_rate,
        batch_size: batch_size,
        minimum_length: minimum_length,
        mixed_orientation: mixed_orientation,
        cores: cores,
        per_sample_sequences: per_sample_sequences,
        untrimmed_sequences: untrimmed_sequences
    }

    command {
        q2dataflow wdl run cutadapt demux_paired ~{write_json(task_params)}
    }

    output {
        File per_sample_sequences_file = "~{per_sample_sequences}"
        File untrimmed_sequences_file = "~{untrimmed_sequences}"
    }

}


workflow wkflw_qiime2_cutadapt_demux_paired {
input {
        File seqs
        String forward_barcodes
        File q2wdl_metafile_forward_barcodes
        String? reverse_barcodes
        File? q2wdl_metafile_reverse_barcodes
        Int forward_cut = 0
        Int reverse_cut = 0
        Boolean anchor_forward_barcode = false
        Boolean anchor_reverse_barcode = false
        Float error_rate = 0.1
        Int batch_size = 0
        Int minimum_length = 1
        Boolean mixed_orientation = false
        Int cores = 1
        String per_sample_sequences
        String untrimmed_sequences
    }

    call qiime2_cutadapt_demux_paired {
        input: seqs=seqs, forward_barcodes=forward_barcodes, q2wdl_metafile_forward_barcodes=q2wdl_metafile_forward_barcodes, reverse_barcodes=reverse_barcodes, q2wdl_metafile_reverse_barcodes=q2wdl_metafile_reverse_barcodes, forward_cut=forward_cut, reverse_cut=reverse_cut, anchor_forward_barcode=anchor_forward_barcode, anchor_reverse_barcode=anchor_reverse_barcode, error_rate=error_rate, batch_size=batch_size, minimum_length=minimum_length, mixed_orientation=mixed_orientation, cores=cores, per_sample_sequences=per_sample_sequences, untrimmed_sequences=untrimmed_sequences
    }

}
