# 
# Copyright (c) 2024, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This template was automatically generated by:
#     q2dataflow wdl (version: 0.2.0)
# for:
#     qiime2 (version: 2024.2.0)
# 


version 1.0

struct qiime2_cutadapt_trim_paired_params {
    File demultiplexed_sequences
    Int cores
    Array[String]? adapter_f
    Array[String]? front_f
    Array[String]? anywhere_f
    Array[String]? adapter_r
    Array[String]? front_r
    Array[String]? anywhere_r
    Float error_rate
    Boolean indels
    Int times
    Int overlap
    Boolean match_read_wildcards
    Boolean match_adapter_wildcards
    Int minimum_length
    Boolean discard_untrimmed
    Float? max_expected_errors
    Float? max_n
    Int quality_cutoff_5end
    Int quality_cutoff_3end
    Int quality_base
    String trimmed_sequences
}

task qiime2_cutadapt_trim_paired {

    input {
        File demultiplexed_sequences
        Int cores = 1
        Array[String]? adapter_f
        Array[String]? front_f
        Array[String]? anywhere_f
        Array[String]? adapter_r
        Array[String]? front_r
        Array[String]? anywhere_r
        Float error_rate = 0.1
        Boolean indels = true
        Int times = 1
        Int overlap = 3
        Boolean match_read_wildcards = false
        Boolean match_adapter_wildcards = true
        Int minimum_length = 1
        Boolean discard_untrimmed = false
        Float? max_expected_errors
        Float? max_n
        Int quality_cutoff_5end = 0
        Int quality_cutoff_3end = 0
        Int quality_base = 33
        String trimmed_sequences
    }

    qiime2_cutadapt_trim_paired_params task_params = object {
        demultiplexed_sequences: demultiplexed_sequences,
        cores: cores,
        adapter_f: adapter_f,
        front_f: front_f,
        anywhere_f: anywhere_f,
        adapter_r: adapter_r,
        front_r: front_r,
        anywhere_r: anywhere_r,
        error_rate: error_rate,
        indels: indels,
        times: times,
        overlap: overlap,
        match_read_wildcards: match_read_wildcards,
        match_adapter_wildcards: match_adapter_wildcards,
        minimum_length: minimum_length,
        discard_untrimmed: discard_untrimmed,
        max_expected_errors: max_expected_errors,
        max_n: max_n,
        quality_cutoff_5end: quality_cutoff_5end,
        quality_cutoff_3end: quality_cutoff_3end,
        quality_base: quality_base,
        trimmed_sequences: trimmed_sequences
    }

    command {
        q2dataflow wdl run cutadapt trim_paired ~{write_json(task_params)}
    }

    output {
        File trimmed_sequences_file = "~{trimmed_sequences}"
    }

}


workflow wkflw_qiime2_cutadapt_trim_paired {
input {
        File demultiplexed_sequences
        Int cores = 1
        Array[String]? adapter_f
        Array[String]? front_f
        Array[String]? anywhere_f
        Array[String]? adapter_r
        Array[String]? front_r
        Array[String]? anywhere_r
        Float error_rate = 0.1
        Boolean indels = true
        Int times = 1
        Int overlap = 3
        Boolean match_read_wildcards = false
        Boolean match_adapter_wildcards = true
        Int minimum_length = 1
        Boolean discard_untrimmed = false
        Float? max_expected_errors
        Float? max_n
        Int quality_cutoff_5end = 0
        Int quality_cutoff_3end = 0
        Int quality_base = 33
        String trimmed_sequences
    }

    call qiime2_cutadapt_trim_paired {
        input: demultiplexed_sequences=demultiplexed_sequences, cores=cores, adapter_f=adapter_f, front_f=front_f, anywhere_f=anywhere_f, adapter_r=adapter_r, front_r=front_r, anywhere_r=anywhere_r, error_rate=error_rate, indels=indels, times=times, overlap=overlap, match_read_wildcards=match_read_wildcards, match_adapter_wildcards=match_adapter_wildcards, minimum_length=minimum_length, discard_untrimmed=discard_untrimmed, max_expected_errors=max_expected_errors, max_n=max_n, quality_cutoff_5end=quality_cutoff_5end, quality_cutoff_3end=quality_cutoff_3end, quality_base=quality_base, trimmed_sequences=trimmed_sequences
    }

}
