# 
# Copyright (c) 2024, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This template was automatically generated by:
#     q2dataflow wdl (version: 0.2.0)
# for:
#     qiime2 (version: 2024.2.0)
# 


version 1.0

struct qiime2_cutadapt_demux_single_params {
    File seqs
    String barcodes
    File q2wdl_metafile_barcodes
    Int cut
    Boolean anchor_barcode
    Float error_rate
    Int batch_size
    Int minimum_length
    Int cores
    String per_sample_sequences
    String untrimmed_sequences
}

task qiime2_cutadapt_demux_single {

    input {
        File seqs
        String barcodes
        File q2wdl_metafile_barcodes
        Int cut = 0
        Boolean anchor_barcode = false
        Float error_rate = 0.1
        Int batch_size = 0
        Int minimum_length = 1
        Int cores = 1
        String per_sample_sequences
        String untrimmed_sequences
    }

    qiime2_cutadapt_demux_single_params task_params = object {
        seqs: seqs,
        barcodes: barcodes,
        q2wdl_metafile_barcodes: q2wdl_metafile_barcodes,
        cut: cut,
        anchor_barcode: anchor_barcode,
        error_rate: error_rate,
        batch_size: batch_size,
        minimum_length: minimum_length,
        cores: cores,
        per_sample_sequences: per_sample_sequences,
        untrimmed_sequences: untrimmed_sequences
    }

    command {
        q2dataflow wdl run cutadapt demux_single ~{write_json(task_params)}
    }

    output {
        File per_sample_sequences_file = "~{per_sample_sequences}"
        File untrimmed_sequences_file = "~{untrimmed_sequences}"
    }

}


workflow wkflw_qiime2_cutadapt_demux_single {
input {
        File seqs
        String barcodes
        File q2wdl_metafile_barcodes
        Int cut = 0
        Boolean anchor_barcode = false
        Float error_rate = 0.1
        Int batch_size = 0
        Int minimum_length = 1
        Int cores = 1
        String per_sample_sequences
        String untrimmed_sequences
    }

    call qiime2_cutadapt_demux_single {
        input: seqs=seqs, barcodes=barcodes, q2wdl_metafile_barcodes=q2wdl_metafile_barcodes, cut=cut, anchor_barcode=anchor_barcode, error_rate=error_rate, batch_size=batch_size, minimum_length=minimum_length, cores=cores, per_sample_sequences=per_sample_sequences, untrimmed_sequences=untrimmed_sequences
    }

}
