# 
# Copyright (c) 2024, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This template was automatically generated by:
#     q2dataflow wdl (version: 0.2.0)
# for:
#     qiime2 (version: 2024.2.0)
# 


version 1.0

struct qiime2_emperor_biplot_params {
    File biplot
    Array[File] q2wdl_metafile_sample_metadata
    Array[File]? q2wdl_metafile_feature_metadata
    Boolean ignore_missing_samples
    Boolean invert
    Int number_of_features
    String visualization
}

task qiime2_emperor_biplot {

    input {
        File biplot
        Array[File] q2wdl_metafile_sample_metadata
        Array[File]? q2wdl_metafile_feature_metadata
        Boolean ignore_missing_samples = false
        Boolean invert = false
        Int number_of_features = 5
        String visualization
    }

    qiime2_emperor_biplot_params task_params = object {
        biplot: biplot,
        q2wdl_metafile_sample_metadata: q2wdl_metafile_sample_metadata,
        q2wdl_metafile_feature_metadata: q2wdl_metafile_feature_metadata,
        ignore_missing_samples: ignore_missing_samples,
        invert: invert,
        number_of_features: number_of_features,
        visualization: visualization
    }

    command {
        q2dataflow wdl run emperor biplot ~{write_json(task_params)}
    }

    output {
        File visualization_file = "~{visualization}"
    }

}


workflow wkflw_qiime2_emperor_biplot {
input {
        File biplot
        Array[File] q2wdl_metafile_sample_metadata
        Array[File]? q2wdl_metafile_feature_metadata
        Boolean ignore_missing_samples = false
        Boolean invert = false
        Int number_of_features = 5
        String visualization
    }

    call qiime2_emperor_biplot {
        input: biplot=biplot, q2wdl_metafile_sample_metadata=q2wdl_metafile_sample_metadata, q2wdl_metafile_feature_metadata=q2wdl_metafile_feature_metadata, ignore_missing_samples=ignore_missing_samples, invert=invert, number_of_features=number_of_features, visualization=visualization
    }

}
