# 
# Copyright (c) 2024, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This template was automatically generated by:
#     q2dataflow wdl (version: 0.2.0)
# for:
#     qiime2 (version: 2024.2.0)
# 


version 1.0

struct qiime2_tools_import_params {
    String type
    String? format
    String import_location
    String output_location
}

task qiime2_tools_import {

    input {
        String type
        String? format
        String import_location
        String output_location
    }

    qiime2_tools_import_params task_params = object {
        type: type,
        format: format,
        import_location: import_location,
        output_location: output_location
    }

    command {
        q2dataflow wdl run tools import ~{write_json(task_params)}
    }

    output {
        File output_location_file = "~{output_location}"
    }

}


workflow wkflw_qiime2_tools_import {
input {
        String type
        String? format
        String import_location
        String output_location
    }

    call qiime2_tools_import {
        input: type=type, format=format, import_location=import_location, output_location=output_location
    }

}
