# 
# Copyright (c) 2024, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This template was automatically generated by:
#     q2dataflow wdl (version: 0.2.0)
# for:
#     qiime2 (version: 2024.2.0)
# 


version 1.0

struct qiime2_composition_add_pseudocount_params {
    File table
    Int pseudocount
    String composition_table
}

task qiime2_composition_add_pseudocount {

    input {
        File table
        Int pseudocount = 1
        String composition_table
    }

    qiime2_composition_add_pseudocount_params task_params = object {
        table: table,
        pseudocount: pseudocount,
        composition_table: composition_table
    }

    command {
        q2dataflow wdl run composition add_pseudocount ~{write_json(task_params)}
    }

    output {
        File composition_table_file = "~{composition_table}"
    }

}


workflow wkflw_qiime2_composition_add_pseudocount {
input {
        File table
        Int pseudocount = 1
        String composition_table
    }

    call qiime2_composition_add_pseudocount {
        input: table=table, pseudocount=pseudocount, composition_table=composition_table
    }

}
