# 
# Copyright (c) 2024, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This template was automatically generated by:
#     q2dataflow wdl (version: 0.2.0)
# for:
#     qiime2 (version: 2024.2.0)
# 


version 1.0

struct qiime2_composition_ancom_params {
    File table
    String metadata
    File q2wdl_metafile_metadata
    String transform_function
    String? difference_function
    Boolean filter_missing
    String visualization
}

task qiime2_composition_ancom {

    input {
        File table
        String metadata
        File q2wdl_metafile_metadata
        String transform_function = "clr"
        String? difference_function
        Boolean filter_missing = false
        String visualization
    }

    qiime2_composition_ancom_params task_params = object {
        table: table,
        metadata: metadata,
        q2wdl_metafile_metadata: q2wdl_metafile_metadata,
        transform_function: transform_function,
        difference_function: difference_function,
        filter_missing: filter_missing,
        visualization: visualization
    }

    command {
        q2dataflow wdl run composition ancom ~{write_json(task_params)}
    }

    output {
        File visualization_file = "~{visualization}"
    }

}


workflow wkflw_qiime2_composition_ancom {
input {
        File table
        String metadata
        File q2wdl_metafile_metadata
        String transform_function = "clr"
        String? difference_function
        Boolean filter_missing = false
        String visualization
    }

    call qiime2_composition_ancom {
        input: table=table, metadata=metadata, q2wdl_metafile_metadata=q2wdl_metafile_metadata, transform_function=transform_function, difference_function=difference_function, filter_missing=filter_missing, visualization=visualization
    }

}
