# 
# Copyright (c) 2023, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This tool was automatically generated by:
#     q2wdl (version: 0.1.0)
# for:
#     qiime2 (version: 2023.2.0)
# 


version 1.0

struct qiime2_phylogeny_filter_tree_params {
    File tree
    File? table
    Array[File]? q2wdl_metafile_metadata
    String? where
    String filtered_tree
}

task qiime2_phylogeny_filter_tree {

    input {
        File tree
        File? table
        Array[File]? q2wdl_metafile_metadata
        String? where
        String filtered_tree
    }

    qiime2_phylogeny_filter_tree_params task_params = object {
        tree: tree,
        table: table,
        q2wdl_metafile_metadata: q2wdl_metafile_metadata,
        where: where,
        filtered_tree: filtered_tree
    }

    command {
        q2dataflow q2wdl run phylogeny filter_tree ~{write_json(task_params)}
    }

    output {
        File filtered_tree_file = "~{filtered_tree}"
    }

}


workflow wkflw_qiime2_phylogeny_filter_tree {
input {
        File tree
        File? table
        Array[File]? q2wdl_metafile_metadata
        String? where
        String filtered_tree
    }

    call qiime2_phylogeny_filter_tree {
        input: tree=tree, table=table, q2wdl_metafile_metadata=q2wdl_metafile_metadata, where=where, filtered_tree=filtered_tree
    }

}
