# 
# Copyright (c) 2023, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This tool was automatically generated by:
#     q2wdl (version: 0.1.0)
# for:
#     qiime2 (version: 2023.2.0)
# 


version 1.0

struct qiime2_phylogeny_align_to_tree_mafft_iqtree_params {
    File sequences
    String n_threads
    Float mask_max_gap_frequency
    Float mask_min_conservation
    String substitution_model
    Boolean fast
    Int? alrt
    Int? seed
    Int? stop_iter
    Float? perturb_nni_strength
    String alignment
    String masked_alignment
    String tree
    String rooted_tree
}

task qiime2_phylogeny_align_to_tree_mafft_iqtree {

    input {
        File sequences
        String n_threads = '1'
        Float mask_max_gap_frequency = 1.0
        Float mask_min_conservation = 0.4
        String substitution_model = "MFP"
        Boolean fast = false
        Int? alrt
        Int? seed
        Int? stop_iter
        Float? perturb_nni_strength
        String alignment
        String masked_alignment
        String tree
        String rooted_tree
    }

    qiime2_phylogeny_align_to_tree_mafft_iqtree_params task_params = object {
        sequences: sequences,
        n_threads: n_threads,
        mask_max_gap_frequency: mask_max_gap_frequency,
        mask_min_conservation: mask_min_conservation,
        substitution_model: substitution_model,
        fast: fast,
        alrt: alrt,
        seed: seed,
        stop_iter: stop_iter,
        perturb_nni_strength: perturb_nni_strength,
        alignment: alignment,
        masked_alignment: masked_alignment,
        tree: tree,
        rooted_tree: rooted_tree
    }

    command {
        q2dataflow q2wdl run phylogeny align_to_tree_mafft_iqtree ~{write_json(task_params)}
    }

    output {
        File alignment_file = "~{alignment}"
        File masked_alignment_file = "~{masked_alignment}"
        File tree_file = "~{tree}"
        File rooted_tree_file = "~{rooted_tree}"
    }

}


workflow wkflw_qiime2_phylogeny_align_to_tree_mafft_iqtree {
input {
        File sequences
        String n_threads = '1'
        Float mask_max_gap_frequency = 1.0
        Float mask_min_conservation = 0.4
        String substitution_model = "MFP"
        Boolean fast = false
        Int? alrt
        Int? seed
        Int? stop_iter
        Float? perturb_nni_strength
        String alignment
        String masked_alignment
        String tree
        String rooted_tree
    }

    call qiime2_phylogeny_align_to_tree_mafft_iqtree {
        input: sequences=sequences, n_threads=n_threads, mask_max_gap_frequency=mask_max_gap_frequency, mask_min_conservation=mask_min_conservation, substitution_model=substitution_model, fast=fast, alrt=alrt, seed=seed, stop_iter=stop_iter, perturb_nni_strength=perturb_nni_strength, alignment=alignment, masked_alignment=masked_alignment, tree=tree, rooted_tree=rooted_tree
    }

}
