# 
# Copyright (c) 2023, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This tool was automatically generated by:
#     q2wdl (version: 0.1.0)
# for:
#     qiime2 (version: 2023.2.0)
# 


version 1.0

struct qiime2_phylogeny_robinson_foulds_params {
    Array[File] trees
    Array[String]? labels
    String missing_tips
    String distance_matrix
}

task qiime2_phylogeny_robinson_foulds {

    input {
        Array[File] trees
        Array[String]? labels
        String missing_tips = "error"
        String distance_matrix
    }

    qiime2_phylogeny_robinson_foulds_params task_params = object {
        trees: trees,
        labels: labels,
        missing_tips: missing_tips,
        distance_matrix: distance_matrix
    }

    command {
        q2dataflow q2wdl run phylogeny robinson_foulds ~{write_json(task_params)}
    }

    output {
        File distance_matrix_file = "~{distance_matrix}"
    }

}


workflow wkflw_qiime2_phylogeny_robinson_foulds {
input {
        Array[File] trees
        Array[String]? labels
        String missing_tips = "error"
        String distance_matrix
    }

    call qiime2_phylogeny_robinson_foulds {
        input: trees=trees, labels=labels, missing_tips=missing_tips, distance_matrix=distance_matrix
    }

}
