# 
# Copyright (c) 2023, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This tool was automatically generated by:
#     q2wdl (version: 0.1.0)
# for:
#     qiime2 (version: 2023.2.0)
# 


version 1.0

struct qiime2_phylogeny_iqtree_params {
    File alignment
    Int? seed
    String n_cores
    Int? n_cores_max
    Int n_runs
    String substitution_model
    Int? n_init_pars_trees
    Int? n_top_init_trees
    Int? n_best_retain_trees
    Int? n_iter
    Int? stop_iter
    Float? perturb_nni_strength
    Int? spr_radius
    Boolean allnni
    Boolean fast
    Int? alrt
    Boolean abayes
    Int? lbp
    Boolean safe
    String tree
}

task qiime2_phylogeny_iqtree {

    input {
        File alignment
        Int? seed
        String n_cores = '1'
        Int? n_cores_max
        Int n_runs = 1
        String substitution_model = "MFP"
        Int? n_init_pars_trees
        Int? n_top_init_trees
        Int? n_best_retain_trees
        Int? n_iter
        Int? stop_iter
        Float? perturb_nni_strength
        Int? spr_radius
        Boolean allnni = false
        Boolean fast = false
        Int? alrt
        Boolean abayes = false
        Int? lbp
        Boolean safe = false
        String tree
    }

    qiime2_phylogeny_iqtree_params task_params = object {
        alignment: alignment,
        seed: seed,
        n_cores: n_cores,
        n_cores_max: n_cores_max,
        n_runs: n_runs,
        substitution_model: substitution_model,
        n_init_pars_trees: n_init_pars_trees,
        n_top_init_trees: n_top_init_trees,
        n_best_retain_trees: n_best_retain_trees,
        n_iter: n_iter,
        stop_iter: stop_iter,
        perturb_nni_strength: perturb_nni_strength,
        spr_radius: spr_radius,
        allnni: allnni,
        fast: fast,
        alrt: alrt,
        abayes: abayes,
        lbp: lbp,
        safe: safe,
        tree: tree
    }

    command {
        q2dataflow q2wdl run phylogeny iqtree ~{write_json(task_params)}
    }

    output {
        File tree_file = "~{tree}"
    }

}


workflow wkflw_qiime2_phylogeny_iqtree {
input {
        File alignment
        Int? seed
        String n_cores = '1'
        Int? n_cores_max
        Int n_runs = 1
        String substitution_model = "MFP"
        Int? n_init_pars_trees
        Int? n_top_init_trees
        Int? n_best_retain_trees
        Int? n_iter
        Int? stop_iter
        Float? perturb_nni_strength
        Int? spr_radius
        Boolean allnni = false
        Boolean fast = false
        Int? alrt
        Boolean abayes = false
        Int? lbp
        Boolean safe = false
        String tree
    }

    call qiime2_phylogeny_iqtree {
        input: alignment=alignment, seed=seed, n_cores=n_cores, n_cores_max=n_cores_max, n_runs=n_runs, substitution_model=substitution_model, n_init_pars_trees=n_init_pars_trees, n_top_init_trees=n_top_init_trees, n_best_retain_trees=n_best_retain_trees, n_iter=n_iter, stop_iter=stop_iter, perturb_nni_strength=perturb_nni_strength, spr_radius=spr_radius, allnni=allnni, fast=fast, alrt=alrt, abayes=abayes, lbp=lbp, safe=safe, tree=tree
    }

}
