# 
# Copyright (c) 2024, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This template was automatically generated by:
#     q2dataflow wdl (version: 0.2.0)
# for:
#     qiime2 (version: 2024.2.0)
# 


version 1.0

struct qiime2_longitudinal_first_differences_params {
    File? table
    Array[File] q2wdl_metafile_metadata
    String state_column
    String individual_id_column
    String metric
    String replicate_handling
    Float? baseline
    String first_differences
}

task qiime2_longitudinal_first_differences {

    input {
        File? table
        Array[File] q2wdl_metafile_metadata
        String state_column
        String individual_id_column
        String metric
        String replicate_handling = "error"
        Float? baseline
        String first_differences
    }

    qiime2_longitudinal_first_differences_params task_params = object {
        table: table,
        q2wdl_metafile_metadata: q2wdl_metafile_metadata,
        state_column: state_column,
        individual_id_column: individual_id_column,
        metric: metric,
        replicate_handling: replicate_handling,
        baseline: baseline,
        first_differences: first_differences
    }

    command {
        q2dataflow wdl run longitudinal first_differences ~{write_json(task_params)}
    }

    output {
        File first_differences_file = "~{first_differences}"
    }

}


workflow wkflw_qiime2_longitudinal_first_differences {
input {
        File? table
        Array[File] q2wdl_metafile_metadata
        String state_column
        String individual_id_column
        String metric
        String replicate_handling = "error"
        Float? baseline
        String first_differences
    }

    call qiime2_longitudinal_first_differences {
        input: table=table, q2wdl_metafile_metadata=q2wdl_metafile_metadata, state_column=state_column, individual_id_column=individual_id_column, metric=metric, replicate_handling=replicate_handling, baseline=baseline, first_differences=first_differences
    }

}
