# 
# Copyright (c) 2024, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This template was automatically generated by:
#     q2dataflow wdl (version: 0.2.0)
# for:
#     qiime2 (version: 2024.2.0)
# 


version 1.0

struct qiime2_longitudinal_pairwise_distances_params {
    File distance_matrix
    Array[File] q2wdl_metafile_metadata
    String group_column
    String state_column
    String state_1
    String state_2
    String individual_id_column
    Boolean parametric
    String palette
    String replicate_handling
    String visualization
}

task qiime2_longitudinal_pairwise_distances {

    input {
        File distance_matrix
        Array[File] q2wdl_metafile_metadata
        String group_column
        String state_column
        String state_1
        String state_2
        String individual_id_column
        Boolean parametric = false
        String palette = "Set1"
        String replicate_handling = "error"
        String visualization
    }

    qiime2_longitudinal_pairwise_distances_params task_params = object {
        distance_matrix: distance_matrix,
        q2wdl_metafile_metadata: q2wdl_metafile_metadata,
        group_column: group_column,
        state_column: state_column,
        state_1: state_1,
        state_2: state_2,
        individual_id_column: individual_id_column,
        parametric: parametric,
        palette: palette,
        replicate_handling: replicate_handling,
        visualization: visualization
    }

    command {
        q2dataflow wdl run longitudinal pairwise_distances ~{write_json(task_params)}
    }

    output {
        File visualization_file = "~{visualization}"
    }

}


workflow wkflw_qiime2_longitudinal_pairwise_distances {
input {
        File distance_matrix
        Array[File] q2wdl_metafile_metadata
        String group_column
        String state_column
        String state_1
        String state_2
        String individual_id_column
        Boolean parametric = false
        String palette = "Set1"
        String replicate_handling = "error"
        String visualization
    }

    call qiime2_longitudinal_pairwise_distances {
        input: distance_matrix=distance_matrix, q2wdl_metafile_metadata=q2wdl_metafile_metadata, group_column=group_column, state_column=state_column, state_1=state_1, state_2=state_2, individual_id_column=individual_id_column, parametric=parametric, palette=palette, replicate_handling=replicate_handling, visualization=visualization
    }

}
