# 
# Copyright (c) 2024, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This template was automatically generated by:
#     q2dataflow wdl (version: 0.2.0)
# for:
#     qiime2 (version: 2024.2.0)
# 


version 1.0

struct qiime2_longitudinal_linear_mixed_effects_params {
    File? table
    Array[File] q2wdl_metafile_metadata
    String state_column
    String individual_id_column
    String? metric
    String? group_columns
    String? random_effects
    String palette
    Boolean lowess
    Float ci
    String? formula
    String visualization
}

task qiime2_longitudinal_linear_mixed_effects {

    input {
        File? table
        Array[File] q2wdl_metafile_metadata
        String state_column
        String individual_id_column
        String? metric
        String? group_columns
        String? random_effects
        String palette = "Set1"
        Boolean lowess = false
        Float ci = 95
        String? formula
        String visualization
    }

    qiime2_longitudinal_linear_mixed_effects_params task_params = object {
        table: table,
        q2wdl_metafile_metadata: q2wdl_metafile_metadata,
        state_column: state_column,
        individual_id_column: individual_id_column,
        metric: metric,
        group_columns: group_columns,
        random_effects: random_effects,
        palette: palette,
        lowess: lowess,
        ci: ci,
        formula: formula,
        visualization: visualization
    }

    command {
        q2dataflow wdl run longitudinal linear_mixed_effects ~{write_json(task_params)}
    }

    output {
        File visualization_file = "~{visualization}"
    }

}


workflow wkflw_qiime2_longitudinal_linear_mixed_effects {
input {
        File? table
        Array[File] q2wdl_metafile_metadata
        String state_column
        String individual_id_column
        String? metric
        String? group_columns
        String? random_effects
        String palette = "Set1"
        Boolean lowess = false
        Float ci = 95
        String? formula
        String visualization
    }

    call qiime2_longitudinal_linear_mixed_effects {
        input: table=table, q2wdl_metafile_metadata=q2wdl_metafile_metadata, state_column=state_column, individual_id_column=individual_id_column, metric=metric, group_columns=group_columns, random_effects=random_effects, palette=palette, lowess=lowess, ci=ci, formula=formula, visualization=visualization
    }

}
