# 
# Copyright (c) 2024, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This template was automatically generated by:
#     q2dataflow wdl (version: 0.2.0)
# for:
#     qiime2 (version: 2024.2.0)
# 


version 1.0

struct qiime2_longitudinal_anova_params {
    Array[File] q2wdl_metafile_metadata
    String formula
    String sstype
    Boolean repeated_measures
    String? individual_id_column
    Boolean rm_aggregate
    String visualization
}

task qiime2_longitudinal_anova {

    input {
        Array[File] q2wdl_metafile_metadata
        String formula
        String sstype = "II"
        Boolean repeated_measures = false
        String? individual_id_column
        Boolean rm_aggregate = false
        String visualization
    }

    qiime2_longitudinal_anova_params task_params = object {
        q2wdl_metafile_metadata: q2wdl_metafile_metadata,
        formula: formula,
        sstype: sstype,
        repeated_measures: repeated_measures,
        individual_id_column: individual_id_column,
        rm_aggregate: rm_aggregate,
        visualization: visualization
    }

    command {
        q2dataflow wdl run longitudinal anova ~{write_json(task_params)}
    }

    output {
        File visualization_file = "~{visualization}"
    }

}


workflow wkflw_qiime2_longitudinal_anova {
input {
        Array[File] q2wdl_metafile_metadata
        String formula
        String sstype = "II"
        Boolean repeated_measures = false
        String? individual_id_column
        Boolean rm_aggregate = false
        String visualization
    }

    call qiime2_longitudinal_anova {
        input: q2wdl_metafile_metadata=q2wdl_metafile_metadata, formula=formula, sstype=sstype, repeated_measures=repeated_measures, individual_id_column=individual_id_column, rm_aggregate=rm_aggregate, visualization=visualization
    }

}
