# 
# Copyright (c) 2023, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This tool was automatically generated by:
#     q2wdl (version: 0.1.0)
# for:
#     qiime2 (version: 2023.2.0)
# 


version 1.0

struct qiime2_feature_classifier_extract_reads_params {
    File sequences
    String f_primer
    String r_primer
    Int trim_right
    Int trunc_len
    Int trim_left
    Float identity
    Int min_length
    Int max_length
    Int n_jobs
    String batch_size
    String read_orientation
    String reads
}

task qiime2_feature_classifier_extract_reads {

    input {
        File sequences
        String f_primer
        String r_primer
        Int trim_right = 0
        Int trunc_len = 0
        Int trim_left = 0
        Float identity = 0.8
        Int min_length = 50
        Int max_length = 0
        Int n_jobs = 1
        String batch_size = 'auto'
        String read_orientation = "both"
        String reads
    }

    qiime2_feature_classifier_extract_reads_params task_params = object {
        sequences: sequences,
        f_primer: f_primer,
        r_primer: r_primer,
        trim_right: trim_right,
        trunc_len: trunc_len,
        trim_left: trim_left,
        identity: identity,
        min_length: min_length,
        max_length: max_length,
        n_jobs: n_jobs,
        batch_size: batch_size,
        read_orientation: read_orientation,
        reads: reads
    }

    command {
        q2dataflow q2wdl run feature_classifier extract_reads ~{write_json(task_params)}
    }

    output {
        File reads_file = "~{reads}"
    }

}


workflow wkflw_qiime2_feature_classifier_extract_reads {
input {
        File sequences
        String f_primer
        String r_primer
        Int trim_right = 0
        Int trunc_len = 0
        Int trim_left = 0
        Float identity = 0.8
        Int min_length = 50
        Int max_length = 0
        Int n_jobs = 1
        String batch_size = 'auto'
        String read_orientation = "both"
        String reads
    }

    call qiime2_feature_classifier_extract_reads {
        input: sequences=sequences, f_primer=f_primer, r_primer=r_primer, trim_right=trim_right, trunc_len=trunc_len, trim_left=trim_left, identity=identity, min_length=min_length, max_length=max_length, n_jobs=n_jobs, batch_size=batch_size, read_orientation=read_orientation, reads=reads
    }

}
