# 
# Copyright (c) 2023, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This tool was automatically generated by:
#     q2wdl (version: 0.1.0)
# for:
#     qiime2 (version: 2023.2.0)
# 


version 1.0

struct qiime2_fragment_insertion_filter_features_params {
    File table
    File tree
    String filtered_table
    String removed_table
}

task qiime2_fragment_insertion_filter_features {

    input {
        File table
        File tree
        String filtered_table
        String removed_table
    }

    qiime2_fragment_insertion_filter_features_params task_params = object {
        table: table,
        tree: tree,
        filtered_table: filtered_table,
        removed_table: removed_table
    }

    command {
        q2dataflow q2wdl run fragment_insertion filter_features ~{write_json(task_params)}
    }

    output {
        File filtered_table_file = "~{filtered_table}"
        File removed_table_file = "~{removed_table}"
    }

}


workflow wkflw_qiime2_fragment_insertion_filter_features {
input {
        File table
        File tree
        String filtered_table
        String removed_table
    }

    call qiime2_fragment_insertion_filter_features {
        input: table=table, tree=tree, filtered_table=filtered_table, removed_table=removed_table
    }

}
