# 
# Copyright (c) 2024, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This template was automatically generated by:
#     q2dataflow wdl (version: 0.2.0)
# for:
#     qiime2 (version: 2024.2.0)
# 


version 1.0

struct qiime2_metadata_shuffle_groups_params {
    String metadata
    File q2wdl_metafile_metadata
    Int n_columns
    String md_column_name_prefix
    String md_column_values_prefix
    Boolean encode_sample_size
    String shuffled_groups
}

task qiime2_metadata_shuffle_groups {

    input {
        String metadata
        File q2wdl_metafile_metadata
        Int n_columns = 3
        String md_column_name_prefix = "shuffled.grouping."
        String md_column_values_prefix = "fake.group."
        Boolean encode_sample_size = false
        String shuffled_groups
    }

    qiime2_metadata_shuffle_groups_params task_params = object {
        metadata: metadata,
        q2wdl_metafile_metadata: q2wdl_metafile_metadata,
        n_columns: n_columns,
        md_column_name_prefix: md_column_name_prefix,
        md_column_values_prefix: md_column_values_prefix,
        encode_sample_size: encode_sample_size,
        shuffled_groups: shuffled_groups
    }

    command {
        q2dataflow wdl run metadata shuffle_groups ~{write_json(task_params)}
    }

    output {
        File shuffled_groups_file = "~{shuffled_groups}"
    }

}


workflow wkflw_qiime2_metadata_shuffle_groups {
input {
        String metadata
        File q2wdl_metafile_metadata
        Int n_columns = 3
        String md_column_name_prefix = "shuffled.grouping."
        String md_column_values_prefix = "fake.group."
        Boolean encode_sample_size = false
        String shuffled_groups
    }

    call qiime2_metadata_shuffle_groups {
        input: metadata=metadata, q2wdl_metafile_metadata=q2wdl_metafile_metadata, n_columns=n_columns, md_column_name_prefix=md_column_name_prefix, md_column_values_prefix=md_column_values_prefix, encode_sample_size=encode_sample_size, shuffled_groups=shuffled_groups
    }

}
