# 
# Copyright (c) 2024, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This template was automatically generated by:
#     q2dataflow wdl (version: 0.2.0)
# for:
#     qiime2 (version: 2024.2.0)
# 


version 1.0

struct qiime2_metadata_distance_matrix_params {
    String metadata
    File q2wdl_metafile_metadata
    String distance_matrix
}

task qiime2_metadata_distance_matrix {

    input {
        String metadata
        File q2wdl_metafile_metadata
        String distance_matrix
    }

    qiime2_metadata_distance_matrix_params task_params = object {
        metadata: metadata,
        q2wdl_metafile_metadata: q2wdl_metafile_metadata,
        distance_matrix: distance_matrix
    }

    command {
        q2dataflow wdl run metadata distance_matrix ~{write_json(task_params)}
    }

    output {
        File distance_matrix_file = "~{distance_matrix}"
    }

}


workflow wkflw_qiime2_metadata_distance_matrix {
input {
        String metadata
        File q2wdl_metafile_metadata
        String distance_matrix
    }

    call qiime2_metadata_distance_matrix {
        input: metadata=metadata, q2wdl_metafile_metadata=q2wdl_metafile_metadata, distance_matrix=distance_matrix
    }

}
