# 
# Copyright (c) 2024, QIIME 2 development team.
# 
# Distributed under the terms of the Modified BSD License. (SPDX: BSD-3-Clause)
# 
# 
# This template was automatically generated by:
#     q2dataflow wdl (version: 0.2.0)
# for:
#     qiime2 (version: 2024.2.0)
# 


version 1.0

struct qiime2_metadata_tabulate_params {
    Array[File] q2wdl_metafile_input
    Int page_size
    String visualization
}

task qiime2_metadata_tabulate {

    input {
        Array[File] q2wdl_metafile_input
        Int page_size = 100
        String visualization
    }

    qiime2_metadata_tabulate_params task_params = object {
        q2wdl_metafile_input: q2wdl_metafile_input,
        page_size: page_size,
        visualization: visualization
    }

    command {
        q2dataflow wdl run metadata tabulate ~{write_json(task_params)}
    }

    output {
        File visualization_file = "~{visualization}"
    }

}


workflow wkflw_qiime2_metadata_tabulate {
input {
        Array[File] q2wdl_metafile_input
        Int page_size = 100
        String visualization
    }

    call qiime2_metadata_tabulate {
        input: q2wdl_metafile_input=q2wdl_metafile_input, page_size=page_size, visualization=visualization
    }

}
